[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
restartPolicyInterval = "30s"
numReplicas = 1

# Resource allocation
[deploy.resources]
cpu = 256
memoryMB = 512

# Environment variables
[env]
NEXT_PUBLIC_API_URL = "https://piquant-desire-production.up.railway.app/api"
NEXT_PUBLIC_WS_URL = "wss://piquant-desire-production.up.railway.app/ws"
