version: '3.8'

services:
  # Backend service for development
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: crypto-bot-backend-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    environment:
      # MEXC API Configuration
      - MEXC_API_KEY=${MEXC_API_KEY}
      - MEXC_SECRET_KEY=${MEXC_SECRET_KEY}
      - MEXC_BASE_URL=${MEXC_BASE_URL:-https://api.mexc.com/api/v3}
      - MEXC_WEBSOCKET_URL=${MEXC_WEBSOCKET_URL:-wss://wbs.mexc.com/ws}
      
      # Turso Database Configuration
      - TURSO_ENABLED=${TURSO_ENABLED:-false}
      - TURSO_URL=${TURSO_URL}
      - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
      - TURSO_SYNC_ENABLED=${TURSO_SYNC_ENABLED:-false}
      - TURSO_SYNC_INTERVAL_SECONDS=${TURSO_SYNC_INTERVAL_SECONDS:-300}
      
      # AI Services Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      
      # Application Configuration
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - DB_PATH=/app/data/dev.db
      - CONFIG_PATH=/app/configs
      - CONFIG_FILE=config.yaml
      - ENVIRONMENT=development
      
      # Authentication Configuration
      - AUTH_ENABLED=${AUTH_ENABLED:-false}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_DOMAIN=${CLERK_DOMAIN}
    networks:
      - crypto-bot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend service for development
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: crypto-bot-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend-dev:
        condition: service_healthy
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080/ws
      - NEXT_PUBLIC_ENV=development
    networks:
      - crypto-bot-network

# Persistent volumes
volumes:
  backend_data:
    driver: local

# Networks
networks:
  crypto-bot-network:
    driver: bridge
