version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crypto-bot-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/app/data
      - ./backend/configs:/app/configs:ro
    environment:
      - MEXC_API_KEY=${MEXC_API_KEY}
      - MEXC_API_SECRET=${MEXC_API_SECRET}
      - MEXC_BASE_URL=${MEXC_BASE_URL:-https://api.mexc.com/api/v3}
      - MEXC_WEBSOCKET_URL=${MEXC_WEBSOCKET_URL:-wss://wbs.mexc.com/ws}
      - TURSO_ENABLED=${TURSO_ENABLED:-false}
      - TURSO_URL=${TURSO_URL}
      - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
      - TURSO_SYNC_ENABLED=${TURSO_SYNC_ENABLED:-false}
      - TURSO_SYNC_INTERVAL_SECONDS=${TURSO_SYNC_INTERVAL_SECONDS:-300}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DB_PATH=/app/data/minimal.db
      - CONFIG_PATH=/app/configs
      - CONFIG_FILE=config.minimal.yaml
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - AUTH_ENABLED=${AUTH_ENABLED:-false}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_DOMAIN=${CLERK_DOMAIN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crypto-bot-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080/api
      - NEXT_PUBLIC_WS_URL=ws://backend:8080/ws
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  backend_data:
    driver: local
