version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crypto-bot-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/data
      - ./backend/configs:/app/configs
    environment:
      - MEXC_API_KEY=${MEXC_API_KEY}
      - MEXC_API_SECRET=${MEXC_API_SECRET}
      - LOG_LEVEL=info
      - DB_PATH=/app/data/db
      - CONFIG_PATH=/app/configs
    command: ["serve", "--port=8080"]
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crypto-bot-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080/api/v1
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  data:
    driver: local
