version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crypto-bot-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/app/data
      - ./backend/configs:/app/configs:ro
    environment:
      # MEXC API Configuration
      - MEXC_API_KEY=${MEXC_API_KEY}
      - MEXC_SECRET_KEY=${MEXC_SECRET_KEY}
      - MEXC_BASE_URL=${MEXC_BASE_URL:-https://api.mexc.com}
      - MEXC_WEBSOCKET_URL=${MEXC_WEBSOCKET_URL:-wss://wbs.mexc.com/ws}

      # Turso Database Configuration
      - TURSO_ENABLED=${TURSO_ENABLED:-false}
      - TURSO_URL=${TURSO_URL}
      - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
      - TURSO_SYNC_ENABLED=${TURSO_SYNC_ENABLED:-false}
      - TURSO_SYNC_INTERVAL_SECONDS=${TURSO_SYNC_INTERVAL_SECONDS:-300}

      # AI Services Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

      # Application Configuration
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DB_PATH=/app/data/minimal.db
      - CONFIG_PATH=/app/configs
      - CONFIG_FILE=config.yaml
      - ENVIRONMENT=${ENVIRONMENT:-development}

      # Authentication Configuration
      - AUTH_ENABLED=${AUTH_ENABLED:-false}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_DOMAIN=${CLERK_DOMAIN}
    networks:
      - crypto-bot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crypto-bot-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080/api
      - NEXT_PUBLIC_WS_URL=ws://backend:8080/ws
      - NEXT_PUBLIC_ENV=${ENVIRONMENT:-development}
    networks:
      - crypto-bot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Development service for frontend (only used in development)
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: crypto-bot-frontend-dev
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080/api
      - NEXT_PUBLIC_WS_URL=ws://backend:8080/ws
      - NEXT_PUBLIC_ENV=development
    networks:
      - crypto-bot-network
    profiles: ["dev"]

# Persistent volumes
volumes:
  backend_data:
    driver: local

# Networks
networks:
  crypto-bot-network:
    driver: bridge
