// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// AuthMiddleware is an autogenerated mock type for the AuthMiddleware type
type AuthMiddleware struct {
	mock.Mock
}

type AuthMiddleware_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthMiddleware) EXPECT() *AuthMiddleware_Expecter {
	return &AuthMiddleware_Expecter{mock: &_m.Mock}
}

// Middleware provides a mock function with no fields
func (_m *AuthMiddleware) Middleware() func(http.Handler) http.Handler {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Middleware")
	}

	var r0 func(http.Handler) http.Handler
	if rf, ok := ret.Get(0).(func() func(http.Handler) http.Handler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(http.Handler) http.Handler)
		}
	}

	return r0
}

// AuthMiddleware_Middleware_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Middleware'
type AuthMiddleware_Middleware_Call struct {
	*mock.Call
}

// Middleware is a helper method to define mock.On call
func (_e *AuthMiddleware_Expecter) Middleware() *AuthMiddleware_Middleware_Call {
	return &AuthMiddleware_Middleware_Call{Call: _e.mock.On("Middleware")}
}

func (_c *AuthMiddleware_Middleware_Call) Run(run func()) *AuthMiddleware_Middleware_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthMiddleware_Middleware_Call) Return(_a0 func(http.Handler) http.Handler) *AuthMiddleware_Middleware_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthMiddleware_Middleware_Call) RunAndReturn(run func() func(http.Handler) http.Handler) *AuthMiddleware_Middleware_Call {
	_c.Call.Return(run)
	return _c
}

// RequireAuthentication provides a mock function with given fields: _a0
func (_m *AuthMiddleware) RequireAuthentication(_a0 http.Handler) http.Handler {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for RequireAuthentication")
	}

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

// AuthMiddleware_RequireAuthentication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireAuthentication'
type AuthMiddleware_RequireAuthentication_Call struct {
	*mock.Call
}

// RequireAuthentication is a helper method to define mock.On call
//   - _a0 http.Handler
func (_e *AuthMiddleware_Expecter) RequireAuthentication(_a0 interface{}) *AuthMiddleware_RequireAuthentication_Call {
	return &AuthMiddleware_RequireAuthentication_Call{Call: _e.mock.On("RequireAuthentication", _a0)}
}

func (_c *AuthMiddleware_RequireAuthentication_Call) Run(run func(_a0 http.Handler)) *AuthMiddleware_RequireAuthentication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Handler))
	})
	return _c
}

func (_c *AuthMiddleware_RequireAuthentication_Call) Return(_a0 http.Handler) *AuthMiddleware_RequireAuthentication_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthMiddleware_RequireAuthentication_Call) RunAndReturn(run func(http.Handler) http.Handler) *AuthMiddleware_RequireAuthentication_Call {
	_c.Call.Return(run)
	return _c
}

// RequireRole provides a mock function with given fields: role
func (_m *AuthMiddleware) RequireRole(role string) func(http.Handler) http.Handler {
	ret := _m.Called(role)

	if len(ret) == 0 {
		panic("no return value specified for RequireRole")
	}

	var r0 func(http.Handler) http.Handler
	if rf, ok := ret.Get(0).(func(string) func(http.Handler) http.Handler); ok {
		r0 = rf(role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(http.Handler) http.Handler)
		}
	}

	return r0
}

// AuthMiddleware_RequireRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireRole'
type AuthMiddleware_RequireRole_Call struct {
	*mock.Call
}

// RequireRole is a helper method to define mock.On call
//   - role string
func (_e *AuthMiddleware_Expecter) RequireRole(role interface{}) *AuthMiddleware_RequireRole_Call {
	return &AuthMiddleware_RequireRole_Call{Call: _e.mock.On("RequireRole", role)}
}

func (_c *AuthMiddleware_RequireRole_Call) Run(run func(role string)) *AuthMiddleware_RequireRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AuthMiddleware_RequireRole_Call) Return(_a0 func(http.Handler) http.Handler) *AuthMiddleware_RequireRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthMiddleware_RequireRole_Call) RunAndReturn(run func(string) func(http.Handler) http.Handler) *AuthMiddleware_RequireRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthMiddleware creates a new instance of AuthMiddleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthMiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthMiddleware {
	mock := &AuthMiddleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
