// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ErrorHandler is an autogenerated mock type for the ErrorHandler type
type ErrorHandler struct {
	mock.Mock
}

type ErrorHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *ErrorHandler) EXPECT() *ErrorHandler_Expecter {
	return &ErrorHandler_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: w, err, traceID
func (_m *ErrorHandler) Execute(w http.ResponseWriter, err error, traceID string) {
	_m.Called(w, err, traceID)
}

// ErrorHandler_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ErrorHandler_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - err error
//   - traceID string
func (_e *ErrorHandler_Expecter) Execute(w interface{}, err interface{}, traceID interface{}) *ErrorHandler_Execute_Call {
	return &ErrorHandler_Execute_Call{Call: _e.mock.On("Execute", w, err, traceID)}
}

func (_c *ErrorHandler_Execute_Call) Run(run func(w http.ResponseWriter, err error, traceID string)) *ErrorHandler_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(error), args[2].(string))
	})
	return _c
}

func (_c *ErrorHandler_Execute_Call) Return() *ErrorHandler_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *ErrorHandler_Execute_Call) RunAndReturn(run func(http.ResponseWriter, error, string)) *ErrorHandler_Execute_Call {
	_c.Run(run)
	return _c
}

// NewErrorHandler creates a new instance of ErrorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrorHandler {
	mock := &ErrorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
