// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	model "github.com/RyanLisse/go-crypto-bot-clean/clean_backend/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// EventBus is an autogenerated mock type for the EventBus type
type EventBus struct {
	mock.Mock
}

type EventBus_Expecter struct {
	mock *mock.Mock
}

func (_m *EventBus) EXPECT() *EventBus_Expecter {
	return &EventBus_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: event
func (_m *EventBus) Publish(event *model.NewCoinEvent) {
	_m.Called(event)
}

// EventBus_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type EventBus_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - event *model.NewCoinEvent
func (_e *EventBus_Expecter) Publish(event interface{}) *EventBus_Publish_Call {
	return &EventBus_Publish_Call{Call: _e.mock.On("Publish", event)}
}

func (_c *EventBus_Publish_Call) Run(run func(event *model.NewCoinEvent)) *EventBus_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.NewCoinEvent))
	})
	return _c
}

func (_c *EventBus_Publish_Call) Return() *EventBus_Publish_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventBus_Publish_Call) RunAndReturn(run func(*model.NewCoinEvent)) *EventBus_Publish_Call {
	_c.Run(run)
	return _c
}

// Subscribe provides a mock function with given fields: callback
func (_m *EventBus) Subscribe(callback func(*model.NewCoinEvent)) error {
	ret := _m.Called(callback)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(func(*model.NewCoinEvent)) error); ok {
		r0 = rf(callback)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventBus_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type EventBus_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - callback func(*model.NewCoinEvent)
func (_e *EventBus_Expecter) Subscribe(callback interface{}) *EventBus_Subscribe_Call {
	return &EventBus_Subscribe_Call{Call: _e.mock.On("Subscribe", callback)}
}

func (_c *EventBus_Subscribe_Call) Run(run func(callback func(*model.NewCoinEvent))) *EventBus_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(*model.NewCoinEvent)))
	})
	return _c
}

func (_c *EventBus_Subscribe_Call) Return(_a0 error) *EventBus_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventBus_Subscribe_Call) RunAndReturn(run func(func(*model.NewCoinEvent)) error) *EventBus_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function with given fields: callback
func (_m *EventBus) Unsubscribe(callback func(*model.NewCoinEvent)) error {
	ret := _m.Called(callback)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(func(*model.NewCoinEvent)) error); ok {
		r0 = rf(callback)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventBus_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type EventBus_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - callback func(*model.NewCoinEvent)
func (_e *EventBus_Expecter) Unsubscribe(callback interface{}) *EventBus_Unsubscribe_Call {
	return &EventBus_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", callback)}
}

func (_c *EventBus_Unsubscribe_Call) Run(run func(callback func(*model.NewCoinEvent))) *EventBus_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(*model.NewCoinEvent)))
	})
	return _c
}

func (_c *EventBus_Unsubscribe_Call) Return(_a0 error) *EventBus_Unsubscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventBus_Unsubscribe_Call) RunAndReturn(run func(func(*model.NewCoinEvent)) error) *EventBus_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventBus creates a new instance of EventBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventBus {
	mock := &EventBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
