// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/RyanLisse/go-crypto-bot-clean/clean_backend/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MarketRepository is an autogenerated mock type for the MarketRepository type
type MarketRepository struct {
	mock.Mock
}

type MarketRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MarketRepository) EXPECT() *MarketRepository_Expecter {
	return &MarketRepository_Expecter{mock: &_m.Mock}
}

// GetAllTickers provides a mock function with given fields: ctx, exchange
func (_m *MarketRepository) GetAllTickers(ctx context.Context, exchange string) ([]*model.Ticker, error) {
	ret := _m.Called(ctx, exchange)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTickers")
	}

	var r0 []*model.Ticker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.Ticker, error)); ok {
		return rf(ctx, exchange)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.Ticker); ok {
		r0 = rf(ctx, exchange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Ticker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, exchange)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketRepository_GetAllTickers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTickers'
type MarketRepository_GetAllTickers_Call struct {
	*mock.Call
}

// GetAllTickers is a helper method to define mock.On call
//   - ctx context.Context
//   - exchange string
func (_e *MarketRepository_Expecter) GetAllTickers(ctx interface{}, exchange interface{}) *MarketRepository_GetAllTickers_Call {
	return &MarketRepository_GetAllTickers_Call{Call: _e.mock.On("GetAllTickers", ctx, exchange)}
}

func (_c *MarketRepository_GetAllTickers_Call) Run(run func(ctx context.Context, exchange string)) *MarketRepository_GetAllTickers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MarketRepository_GetAllTickers_Call) Return(_a0 []*model.Ticker, _a1 error) *MarketRepository_GetAllTickers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketRepository_GetAllTickers_Call) RunAndReturn(run func(context.Context, string) ([]*model.Ticker, error)) *MarketRepository_GetAllTickers_Call {
	_c.Call.Return(run)
	return _c
}

// GetKline provides a mock function with given fields: ctx, symbol, exchange, interval, openTime
func (_m *MarketRepository) GetKline(ctx context.Context, symbol string, exchange string, interval model.KlineInterval, openTime time.Time) (*model.Kline, error) {
	ret := _m.Called(ctx, symbol, exchange, interval, openTime)

	if len(ret) == 0 {
		panic("no return value specified for GetKline")
	}

	var r0 *model.Kline
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.KlineInterval, time.Time) (*model.Kline, error)); ok {
		return rf(ctx, symbol, exchange, interval, openTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.KlineInterval, time.Time) *model.Kline); ok {
		r0 = rf(ctx, symbol, exchange, interval, openTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Kline)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, model.KlineInterval, time.Time) error); ok {
		r1 = rf(ctx, symbol, exchange, interval, openTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketRepository_GetKline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKline'
type MarketRepository_GetKline_Call struct {
	*mock.Call
}

// GetKline is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - exchange string
//   - interval model.KlineInterval
//   - openTime time.Time
func (_e *MarketRepository_Expecter) GetKline(ctx interface{}, symbol interface{}, exchange interface{}, interval interface{}, openTime interface{}) *MarketRepository_GetKline_Call {
	return &MarketRepository_GetKline_Call{Call: _e.mock.On("GetKline", ctx, symbol, exchange, interval, openTime)}
}

func (_c *MarketRepository_GetKline_Call) Run(run func(ctx context.Context, symbol string, exchange string, interval model.KlineInterval, openTime time.Time)) *MarketRepository_GetKline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.KlineInterval), args[4].(time.Time))
	})
	return _c
}

func (_c *MarketRepository_GetKline_Call) Return(_a0 *model.Kline, _a1 error) *MarketRepository_GetKline_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketRepository_GetKline_Call) RunAndReturn(run func(context.Context, string, string, model.KlineInterval, time.Time) (*model.Kline, error)) *MarketRepository_GetKline_Call {
	_c.Call.Return(run)
	return _c
}

// GetKlines provides a mock function with given fields: ctx, symbol, exchange, interval, start, end, limit
func (_m *MarketRepository) GetKlines(ctx context.Context, symbol string, exchange string, interval model.KlineInterval, start time.Time, end time.Time, limit int) ([]*model.Kline, error) {
	ret := _m.Called(ctx, symbol, exchange, interval, start, end, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetKlines")
	}

	var r0 []*model.Kline
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.KlineInterval, time.Time, time.Time, int) ([]*model.Kline, error)); ok {
		return rf(ctx, symbol, exchange, interval, start, end, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.KlineInterval, time.Time, time.Time, int) []*model.Kline); ok {
		r0 = rf(ctx, symbol, exchange, interval, start, end, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Kline)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, model.KlineInterval, time.Time, time.Time, int) error); ok {
		r1 = rf(ctx, symbol, exchange, interval, start, end, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketRepository_GetKlines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKlines'
type MarketRepository_GetKlines_Call struct {
	*mock.Call
}

// GetKlines is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - exchange string
//   - interval model.KlineInterval
//   - start time.Time
//   - end time.Time
//   - limit int
func (_e *MarketRepository_Expecter) GetKlines(ctx interface{}, symbol interface{}, exchange interface{}, interval interface{}, start interface{}, end interface{}, limit interface{}) *MarketRepository_GetKlines_Call {
	return &MarketRepository_GetKlines_Call{Call: _e.mock.On("GetKlines", ctx, symbol, exchange, interval, start, end, limit)}
}

func (_c *MarketRepository_GetKlines_Call) Run(run func(ctx context.Context, symbol string, exchange string, interval model.KlineInterval, start time.Time, end time.Time, limit int)) *MarketRepository_GetKlines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.KlineInterval), args[4].(time.Time), args[5].(time.Time), args[6].(int))
	})
	return _c
}

func (_c *MarketRepository_GetKlines_Call) Return(_a0 []*model.Kline, _a1 error) *MarketRepository_GetKlines_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketRepository_GetKlines_Call) RunAndReturn(run func(context.Context, string, string, model.KlineInterval, time.Time, time.Time, int) ([]*model.Kline, error)) *MarketRepository_GetKlines_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestKline provides a mock function with given fields: ctx, symbol, exchange, interval
func (_m *MarketRepository) GetLatestKline(ctx context.Context, symbol string, exchange string, interval model.KlineInterval) (*model.Kline, error) {
	ret := _m.Called(ctx, symbol, exchange, interval)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestKline")
	}

	var r0 *model.Kline
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.KlineInterval) (*model.Kline, error)); ok {
		return rf(ctx, symbol, exchange, interval)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.KlineInterval) *model.Kline); ok {
		r0 = rf(ctx, symbol, exchange, interval)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Kline)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, model.KlineInterval) error); ok {
		r1 = rf(ctx, symbol, exchange, interval)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketRepository_GetLatestKline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestKline'
type MarketRepository_GetLatestKline_Call struct {
	*mock.Call
}

// GetLatestKline is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - exchange string
//   - interval model.KlineInterval
func (_e *MarketRepository_Expecter) GetLatestKline(ctx interface{}, symbol interface{}, exchange interface{}, interval interface{}) *MarketRepository_GetLatestKline_Call {
	return &MarketRepository_GetLatestKline_Call{Call: _e.mock.On("GetLatestKline", ctx, symbol, exchange, interval)}
}

func (_c *MarketRepository_GetLatestKline_Call) Run(run func(ctx context.Context, symbol string, exchange string, interval model.KlineInterval)) *MarketRepository_GetLatestKline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.KlineInterval))
	})
	return _c
}

func (_c *MarketRepository_GetLatestKline_Call) Return(_a0 *model.Kline, _a1 error) *MarketRepository_GetLatestKline_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketRepository_GetLatestKline_Call) RunAndReturn(run func(context.Context, string, string, model.KlineInterval) (*model.Kline, error)) *MarketRepository_GetLatestKline_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestTickers provides a mock function with given fields: ctx, limit
func (_m *MarketRepository) GetLatestTickers(ctx context.Context, limit int) ([]*model.Ticker, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestTickers")
	}

	var r0 []*model.Ticker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*model.Ticker, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*model.Ticker); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Ticker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketRepository_GetLatestTickers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestTickers'
type MarketRepository_GetLatestTickers_Call struct {
	*mock.Call
}

// GetLatestTickers is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MarketRepository_Expecter) GetLatestTickers(ctx interface{}, limit interface{}) *MarketRepository_GetLatestTickers_Call {
	return &MarketRepository_GetLatestTickers_Call{Call: _e.mock.On("GetLatestTickers", ctx, limit)}
}

func (_c *MarketRepository_GetLatestTickers_Call) Run(run func(ctx context.Context, limit int)) *MarketRepository_GetLatestTickers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MarketRepository_GetLatestTickers_Call) Return(_a0 []*model.Ticker, _a1 error) *MarketRepository_GetLatestTickers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketRepository_GetLatestTickers_Call) RunAndReturn(run func(context.Context, int) ([]*model.Ticker, error)) *MarketRepository_GetLatestTickers_Call {
	_c.Call.Return(run)
	return _c
}

// GetTicker provides a mock function with given fields: ctx, symbol, exchange
func (_m *MarketRepository) GetTicker(ctx context.Context, symbol string, exchange string) (*model.Ticker, error) {
	ret := _m.Called(ctx, symbol, exchange)

	if len(ret) == 0 {
		panic("no return value specified for GetTicker")
	}

	var r0 *model.Ticker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Ticker, error)); ok {
		return rf(ctx, symbol, exchange)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Ticker); ok {
		r0 = rf(ctx, symbol, exchange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Ticker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, symbol, exchange)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketRepository_GetTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTicker'
type MarketRepository_GetTicker_Call struct {
	*mock.Call
}

// GetTicker is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - exchange string
func (_e *MarketRepository_Expecter) GetTicker(ctx interface{}, symbol interface{}, exchange interface{}) *MarketRepository_GetTicker_Call {
	return &MarketRepository_GetTicker_Call{Call: _e.mock.On("GetTicker", ctx, symbol, exchange)}
}

func (_c *MarketRepository_GetTicker_Call) Run(run func(ctx context.Context, symbol string, exchange string)) *MarketRepository_GetTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MarketRepository_GetTicker_Call) Return(_a0 *model.Ticker, _a1 error) *MarketRepository_GetTicker_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketRepository_GetTicker_Call) RunAndReturn(run func(context.Context, string, string) (*model.Ticker, error)) *MarketRepository_GetTicker_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeOldData provides a mock function with given fields: ctx, olderThan
func (_m *MarketRepository) PurgeOldData(ctx context.Context, olderThan time.Time) error {
	ret := _m.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for PurgeOldData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) error); ok {
		r0 = rf(ctx, olderThan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarketRepository_PurgeOldData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeOldData'
type MarketRepository_PurgeOldData_Call struct {
	*mock.Call
}

// PurgeOldData is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Time
func (_e *MarketRepository_Expecter) PurgeOldData(ctx interface{}, olderThan interface{}) *MarketRepository_PurgeOldData_Call {
	return &MarketRepository_PurgeOldData_Call{Call: _e.mock.On("PurgeOldData", ctx, olderThan)}
}

func (_c *MarketRepository_PurgeOldData_Call) Run(run func(ctx context.Context, olderThan time.Time)) *MarketRepository_PurgeOldData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MarketRepository_PurgeOldData_Call) Return(_a0 error) *MarketRepository_PurgeOldData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MarketRepository_PurgeOldData_Call) RunAndReturn(run func(context.Context, time.Time) error) *MarketRepository_PurgeOldData_Call {
	_c.Call.Return(run)
	return _c
}

// SaveKline provides a mock function with given fields: ctx, kline
func (_m *MarketRepository) SaveKline(ctx context.Context, kline *model.Kline) error {
	ret := _m.Called(ctx, kline)

	if len(ret) == 0 {
		panic("no return value specified for SaveKline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Kline) error); ok {
		r0 = rf(ctx, kline)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarketRepository_SaveKline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveKline'
type MarketRepository_SaveKline_Call struct {
	*mock.Call
}

// SaveKline is a helper method to define mock.On call
//   - ctx context.Context
//   - kline *model.Kline
func (_e *MarketRepository_Expecter) SaveKline(ctx interface{}, kline interface{}) *MarketRepository_SaveKline_Call {
	return &MarketRepository_SaveKline_Call{Call: _e.mock.On("SaveKline", ctx, kline)}
}

func (_c *MarketRepository_SaveKline_Call) Run(run func(ctx context.Context, kline *model.Kline)) *MarketRepository_SaveKline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Kline))
	})
	return _c
}

func (_c *MarketRepository_SaveKline_Call) Return(_a0 error) *MarketRepository_SaveKline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MarketRepository_SaveKline_Call) RunAndReturn(run func(context.Context, *model.Kline) error) *MarketRepository_SaveKline_Call {
	_c.Call.Return(run)
	return _c
}

// SaveKlines provides a mock function with given fields: ctx, klines
func (_m *MarketRepository) SaveKlines(ctx context.Context, klines []*model.Kline) error {
	ret := _m.Called(ctx, klines)

	if len(ret) == 0 {
		panic("no return value specified for SaveKlines")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*model.Kline) error); ok {
		r0 = rf(ctx, klines)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarketRepository_SaveKlines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveKlines'
type MarketRepository_SaveKlines_Call struct {
	*mock.Call
}

// SaveKlines is a helper method to define mock.On call
//   - ctx context.Context
//   - klines []*model.Kline
func (_e *MarketRepository_Expecter) SaveKlines(ctx interface{}, klines interface{}) *MarketRepository_SaveKlines_Call {
	return &MarketRepository_SaveKlines_Call{Call: _e.mock.On("SaveKlines", ctx, klines)}
}

func (_c *MarketRepository_SaveKlines_Call) Run(run func(ctx context.Context, klines []*model.Kline)) *MarketRepository_SaveKlines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*model.Kline))
	})
	return _c
}

func (_c *MarketRepository_SaveKlines_Call) Return(_a0 error) *MarketRepository_SaveKlines_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MarketRepository_SaveKlines_Call) RunAndReturn(run func(context.Context, []*model.Kline) error) *MarketRepository_SaveKlines_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTicker provides a mock function with given fields: ctx, ticker
func (_m *MarketRepository) SaveTicker(ctx context.Context, ticker *model.Ticker) error {
	ret := _m.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for SaveTicker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Ticker) error); ok {
		r0 = rf(ctx, ticker)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarketRepository_SaveTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTicker'
type MarketRepository_SaveTicker_Call struct {
	*mock.Call
}

// SaveTicker is a helper method to define mock.On call
//   - ctx context.Context
//   - ticker *model.Ticker
func (_e *MarketRepository_Expecter) SaveTicker(ctx interface{}, ticker interface{}) *MarketRepository_SaveTicker_Call {
	return &MarketRepository_SaveTicker_Call{Call: _e.mock.On("SaveTicker", ctx, ticker)}
}

func (_c *MarketRepository_SaveTicker_Call) Run(run func(ctx context.Context, ticker *model.Ticker)) *MarketRepository_SaveTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Ticker))
	})
	return _c
}

func (_c *MarketRepository_SaveTicker_Call) Return(_a0 error) *MarketRepository_SaveTicker_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MarketRepository_SaveTicker_Call) RunAndReturn(run func(context.Context, *model.Ticker) error) *MarketRepository_SaveTicker_Call {
	_c.Call.Return(run)
	return _c
}

// NewMarketRepository creates a new instance of MarketRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketRepository {
	mock := &MarketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
