// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/RyanLisse/go-crypto-bot-clean/clean_backend/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MarketService is an autogenerated mock type for the MarketService type
type MarketService struct {
	mock.Mock
}

type MarketService_Expecter struct {
	mock *mock.Mock
}

func (_m *MarketService) EXPECT() *MarketService_Expecter {
	return &MarketService_Expecter{mock: &_m.Mock}
}

// GetAllSymbols provides a mock function with given fields: ctx, exchange
func (_m *MarketService) GetAllSymbols(ctx context.Context, exchange string) ([]*model.Symbol, error) {
	ret := _m.Called(ctx, exchange)

	if len(ret) == 0 {
		panic("no return value specified for GetAllSymbols")
	}

	var r0 []*model.Symbol
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.Symbol, error)); ok {
		return rf(ctx, exchange)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.Symbol); ok {
		r0 = rf(ctx, exchange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Symbol)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, exchange)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketService_GetAllSymbols_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllSymbols'
type MarketService_GetAllSymbols_Call struct {
	*mock.Call
}

// GetAllSymbols is a helper method to define mock.On call
//   - ctx context.Context
//   - exchange string
func (_e *MarketService_Expecter) GetAllSymbols(ctx interface{}, exchange interface{}) *MarketService_GetAllSymbols_Call {
	return &MarketService_GetAllSymbols_Call{Call: _e.mock.On("GetAllSymbols", ctx, exchange)}
}

func (_c *MarketService_GetAllSymbols_Call) Run(run func(ctx context.Context, exchange string)) *MarketService_GetAllSymbols_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MarketService_GetAllSymbols_Call) Return(_a0 []*model.Symbol, _a1 error) *MarketService_GetAllSymbols_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketService_GetAllSymbols_Call) RunAndReturn(run func(context.Context, string) ([]*model.Symbol, error)) *MarketService_GetAllSymbols_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTickers provides a mock function with given fields: ctx, exchange
func (_m *MarketService) GetAllTickers(ctx context.Context, exchange string) ([]*model.Ticker, error) {
	ret := _m.Called(ctx, exchange)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTickers")
	}

	var r0 []*model.Ticker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.Ticker, error)); ok {
		return rf(ctx, exchange)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.Ticker); ok {
		r0 = rf(ctx, exchange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Ticker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, exchange)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketService_GetAllTickers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTickers'
type MarketService_GetAllTickers_Call struct {
	*mock.Call
}

// GetAllTickers is a helper method to define mock.On call
//   - ctx context.Context
//   - exchange string
func (_e *MarketService_Expecter) GetAllTickers(ctx interface{}, exchange interface{}) *MarketService_GetAllTickers_Call {
	return &MarketService_GetAllTickers_Call{Call: _e.mock.On("GetAllTickers", ctx, exchange)}
}

func (_c *MarketService_GetAllTickers_Call) Run(run func(ctx context.Context, exchange string)) *MarketService_GetAllTickers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MarketService_GetAllTickers_Call) Return(_a0 []*model.Ticker, _a1 error) *MarketService_GetAllTickers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketService_GetAllTickers_Call) RunAndReturn(run func(context.Context, string) ([]*model.Ticker, error)) *MarketService_GetAllTickers_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistoricalKlines provides a mock function with given fields: ctx, symbol, exchange, interval, startTime, endTime, limit
func (_m *MarketService) GetHistoricalKlines(ctx context.Context, symbol string, exchange string, interval model.KlineInterval, startTime time.Time, endTime time.Time, limit int) ([]*model.Kline, error) {
	ret := _m.Called(ctx, symbol, exchange, interval, startTime, endTime, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoricalKlines")
	}

	var r0 []*model.Kline
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.KlineInterval, time.Time, time.Time, int) ([]*model.Kline, error)); ok {
		return rf(ctx, symbol, exchange, interval, startTime, endTime, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.KlineInterval, time.Time, time.Time, int) []*model.Kline); ok {
		r0 = rf(ctx, symbol, exchange, interval, startTime, endTime, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Kline)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, model.KlineInterval, time.Time, time.Time, int) error); ok {
		r1 = rf(ctx, symbol, exchange, interval, startTime, endTime, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketService_GetHistoricalKlines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistoricalKlines'
type MarketService_GetHistoricalKlines_Call struct {
	*mock.Call
}

// GetHistoricalKlines is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - exchange string
//   - interval model.KlineInterval
//   - startTime time.Time
//   - endTime time.Time
//   - limit int
func (_e *MarketService_Expecter) GetHistoricalKlines(ctx interface{}, symbol interface{}, exchange interface{}, interval interface{}, startTime interface{}, endTime interface{}, limit interface{}) *MarketService_GetHistoricalKlines_Call {
	return &MarketService_GetHistoricalKlines_Call{Call: _e.mock.On("GetHistoricalKlines", ctx, symbol, exchange, interval, startTime, endTime, limit)}
}

func (_c *MarketService_GetHistoricalKlines_Call) Run(run func(ctx context.Context, symbol string, exchange string, interval model.KlineInterval, startTime time.Time, endTime time.Time, limit int)) *MarketService_GetHistoricalKlines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.KlineInterval), args[4].(time.Time), args[5].(time.Time), args[6].(int))
	})
	return _c
}

func (_c *MarketService_GetHistoricalKlines_Call) Return(_a0 []*model.Kline, _a1 error) *MarketService_GetHistoricalKlines_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketService_GetHistoricalKlines_Call) RunAndReturn(run func(context.Context, string, string, model.KlineInterval, time.Time, time.Time, int) ([]*model.Kline, error)) *MarketService_GetHistoricalKlines_Call {
	_c.Call.Return(run)
	return _c
}

// GetKlines provides a mock function with given fields: ctx, symbol, exchange, interval, limit
func (_m *MarketService) GetKlines(ctx context.Context, symbol string, exchange string, interval model.KlineInterval, limit int) ([]*model.Kline, error) {
	ret := _m.Called(ctx, symbol, exchange, interval, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetKlines")
	}

	var r0 []*model.Kline
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.KlineInterval, int) ([]*model.Kline, error)); ok {
		return rf(ctx, symbol, exchange, interval, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.KlineInterval, int) []*model.Kline); ok {
		r0 = rf(ctx, symbol, exchange, interval, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Kline)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, model.KlineInterval, int) error); ok {
		r1 = rf(ctx, symbol, exchange, interval, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketService_GetKlines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKlines'
type MarketService_GetKlines_Call struct {
	*mock.Call
}

// GetKlines is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - exchange string
//   - interval model.KlineInterval
//   - limit int
func (_e *MarketService_Expecter) GetKlines(ctx interface{}, symbol interface{}, exchange interface{}, interval interface{}, limit interface{}) *MarketService_GetKlines_Call {
	return &MarketService_GetKlines_Call{Call: _e.mock.On("GetKlines", ctx, symbol, exchange, interval, limit)}
}

func (_c *MarketService_GetKlines_Call) Run(run func(ctx context.Context, symbol string, exchange string, interval model.KlineInterval, limit int)) *MarketService_GetKlines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.KlineInterval), args[4].(int))
	})
	return _c
}

func (_c *MarketService_GetKlines_Call) Return(_a0 []*model.Kline, _a1 error) *MarketService_GetKlines_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketService_GetKlines_Call) RunAndReturn(run func(context.Context, string, string, model.KlineInterval, int) ([]*model.Kline, error)) *MarketService_GetKlines_Call {
	_c.Call.Return(run)
	return _c
}

// GetSymbol provides a mock function with given fields: ctx, symbol, exchange
func (_m *MarketService) GetSymbol(ctx context.Context, symbol string, exchange string) (*model.Symbol, error) {
	ret := _m.Called(ctx, symbol, exchange)

	if len(ret) == 0 {
		panic("no return value specified for GetSymbol")
	}

	var r0 *model.Symbol
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Symbol, error)); ok {
		return rf(ctx, symbol, exchange)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Symbol); ok {
		r0 = rf(ctx, symbol, exchange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Symbol)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, symbol, exchange)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketService_GetSymbol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSymbol'
type MarketService_GetSymbol_Call struct {
	*mock.Call
}

// GetSymbol is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - exchange string
func (_e *MarketService_Expecter) GetSymbol(ctx interface{}, symbol interface{}, exchange interface{}) *MarketService_GetSymbol_Call {
	return &MarketService_GetSymbol_Call{Call: _e.mock.On("GetSymbol", ctx, symbol, exchange)}
}

func (_c *MarketService_GetSymbol_Call) Run(run func(ctx context.Context, symbol string, exchange string)) *MarketService_GetSymbol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MarketService_GetSymbol_Call) Return(_a0 *model.Symbol, _a1 error) *MarketService_GetSymbol_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketService_GetSymbol_Call) RunAndReturn(run func(context.Context, string, string) (*model.Symbol, error)) *MarketService_GetSymbol_Call {
	_c.Call.Return(run)
	return _c
}

// GetTicker provides a mock function with given fields: ctx, symbol, exchange
func (_m *MarketService) GetTicker(ctx context.Context, symbol string, exchange string) (*model.Ticker, error) {
	ret := _m.Called(ctx, symbol, exchange)

	if len(ret) == 0 {
		panic("no return value specified for GetTicker")
	}

	var r0 *model.Ticker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Ticker, error)); ok {
		return rf(ctx, symbol, exchange)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Ticker); ok {
		r0 = rf(ctx, symbol, exchange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Ticker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, symbol, exchange)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketService_GetTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTicker'
type MarketService_GetTicker_Call struct {
	*mock.Call
}

// GetTicker is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - exchange string
func (_e *MarketService_Expecter) GetTicker(ctx interface{}, symbol interface{}, exchange interface{}) *MarketService_GetTicker_Call {
	return &MarketService_GetTicker_Call{Call: _e.mock.On("GetTicker", ctx, symbol, exchange)}
}

func (_c *MarketService_GetTicker_Call) Run(run func(ctx context.Context, symbol string, exchange string)) *MarketService_GetTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MarketService_GetTicker_Call) Return(_a0 *model.Ticker, _a1 error) *MarketService_GetTicker_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketService_GetTicker_Call) RunAndReturn(run func(context.Context, string, string) (*model.Ticker, error)) *MarketService_GetTicker_Call {
	_c.Call.Return(run)
	return _c
}

// SyncMarketData provides a mock function with given fields: ctx, exchange
func (_m *MarketService) SyncMarketData(ctx context.Context, exchange string) error {
	ret := _m.Called(ctx, exchange)

	if len(ret) == 0 {
		panic("no return value specified for SyncMarketData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, exchange)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarketService_SyncMarketData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncMarketData'
type MarketService_SyncMarketData_Call struct {
	*mock.Call
}

// SyncMarketData is a helper method to define mock.On call
//   - ctx context.Context
//   - exchange string
func (_e *MarketService_Expecter) SyncMarketData(ctx interface{}, exchange interface{}) *MarketService_SyncMarketData_Call {
	return &MarketService_SyncMarketData_Call{Call: _e.mock.On("SyncMarketData", ctx, exchange)}
}

func (_c *MarketService_SyncMarketData_Call) Run(run func(ctx context.Context, exchange string)) *MarketService_SyncMarketData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MarketService_SyncMarketData_Call) Return(_a0 error) *MarketService_SyncMarketData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MarketService_SyncMarketData_Call) RunAndReturn(run func(context.Context, string) error) *MarketService_SyncMarketData_Call {
	_c.Call.Return(run)
	return _c
}

// SyncSymbols provides a mock function with given fields: ctx, exchange
func (_m *MarketService) SyncSymbols(ctx context.Context, exchange string) error {
	ret := _m.Called(ctx, exchange)

	if len(ret) == 0 {
		panic("no return value specified for SyncSymbols")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, exchange)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarketService_SyncSymbols_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncSymbols'
type MarketService_SyncSymbols_Call struct {
	*mock.Call
}

// SyncSymbols is a helper method to define mock.On call
//   - ctx context.Context
//   - exchange string
func (_e *MarketService_Expecter) SyncSymbols(ctx interface{}, exchange interface{}) *MarketService_SyncSymbols_Call {
	return &MarketService_SyncSymbols_Call{Call: _e.mock.On("SyncSymbols", ctx, exchange)}
}

func (_c *MarketService_SyncSymbols_Call) Run(run func(ctx context.Context, exchange string)) *MarketService_SyncSymbols_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MarketService_SyncSymbols_Call) Return(_a0 error) *MarketService_SyncSymbols_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MarketService_SyncSymbols_Call) RunAndReturn(run func(context.Context, string) error) *MarketService_SyncSymbols_Call {
	_c.Call.Return(run)
	return _c
}

// NewMarketService creates a new instance of MarketService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketService {
	mock := &MarketService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
