// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/RyanLisse/go-crypto-bot-clean/clean_backend/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MEXCClient is an autogenerated mock type for the MEXCClient type
type MEXCClient struct {
	mock.Mock
}

type MEXCClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MEXCClient) EXPECT() *MEXCClient_Expecter {
	return &MEXCClient_Expecter{mock: &_m.Mock}
}

// GetExchangeInfo provides a mock function with given fields: ctx
func (_m *MEXCClient) GetExchangeInfo(ctx context.Context) (*model.ExchangeInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExchangeInfo")
	}

	var r0 *model.ExchangeInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*model.ExchangeInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *model.ExchangeInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ExchangeInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MEXCClient_GetExchangeInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExchangeInfo'
type MEXCClient_GetExchangeInfo_Call struct {
	*mock.Call
}

// GetExchangeInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MEXCClient_Expecter) GetExchangeInfo(ctx interface{}) *MEXCClient_GetExchangeInfo_Call {
	return &MEXCClient_GetExchangeInfo_Call{Call: _e.mock.On("GetExchangeInfo", ctx)}
}

func (_c *MEXCClient_GetExchangeInfo_Call) Run(run func(ctx context.Context)) *MEXCClient_GetExchangeInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MEXCClient_GetExchangeInfo_Call) Return(_a0 *model.ExchangeInfo, _a1 error) *MEXCClient_GetExchangeInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MEXCClient_GetExchangeInfo_Call) RunAndReturn(run func(context.Context) (*model.ExchangeInfo, error)) *MEXCClient_GetExchangeInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetKlines provides a mock function with given fields: ctx, symbol, interval, limit
func (_m *MEXCClient) GetKlines(ctx context.Context, symbol string, interval model.KlineInterval, limit int) ([]*model.Kline, error) {
	ret := _m.Called(ctx, symbol, interval, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetKlines")
	}

	var r0 []*model.Kline
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.KlineInterval, int) ([]*model.Kline, error)); ok {
		return rf(ctx, symbol, interval, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.KlineInterval, int) []*model.Kline); ok {
		r0 = rf(ctx, symbol, interval, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Kline)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.KlineInterval, int) error); ok {
		r1 = rf(ctx, symbol, interval, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MEXCClient_GetKlines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKlines'
type MEXCClient_GetKlines_Call struct {
	*mock.Call
}

// GetKlines is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - interval model.KlineInterval
//   - limit int
func (_e *MEXCClient_Expecter) GetKlines(ctx interface{}, symbol interface{}, interval interface{}, limit interface{}) *MEXCClient_GetKlines_Call {
	return &MEXCClient_GetKlines_Call{Call: _e.mock.On("GetKlines", ctx, symbol, interval, limit)}
}

func (_c *MEXCClient_GetKlines_Call) Run(run func(ctx context.Context, symbol string, interval model.KlineInterval, limit int)) *MEXCClient_GetKlines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.KlineInterval), args[3].(int))
	})
	return _c
}

func (_c *MEXCClient_GetKlines_Call) Return(_a0 []*model.Kline, _a1 error) *MEXCClient_GetKlines_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MEXCClient_GetKlines_Call) RunAndReturn(run func(context.Context, string, model.KlineInterval, int) ([]*model.Kline, error)) *MEXCClient_GetKlines_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarketData provides a mock function with given fields: ctx, symbol
func (_m *MEXCClient) GetMarketData(ctx context.Context, symbol string) (*model.Ticker, error) {
	ret := _m.Called(ctx, symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetMarketData")
	}

	var r0 *model.Ticker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Ticker, error)); ok {
		return rf(ctx, symbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Ticker); ok {
		r0 = rf(ctx, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Ticker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MEXCClient_GetMarketData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarketData'
type MEXCClient_GetMarketData_Call struct {
	*mock.Call
}

// GetMarketData is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
func (_e *MEXCClient_Expecter) GetMarketData(ctx interface{}, symbol interface{}) *MEXCClient_GetMarketData_Call {
	return &MEXCClient_GetMarketData_Call{Call: _e.mock.On("GetMarketData", ctx, symbol)}
}

func (_c *MEXCClient_GetMarketData_Call) Run(run func(ctx context.Context, symbol string)) *MEXCClient_GetMarketData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MEXCClient_GetMarketData_Call) Return(_a0 *model.Ticker, _a1 error) *MEXCClient_GetMarketData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MEXCClient_GetMarketData_Call) RunAndReturn(run func(context.Context, string) (*model.Ticker, error)) *MEXCClient_GetMarketData_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderBook provides a mock function with given fields: ctx, symbol, depth
func (_m *MEXCClient) GetOrderBook(ctx context.Context, symbol string, depth int) (*model.OrderBook, error) {
	ret := _m.Called(ctx, symbol, depth)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderBook")
	}

	var r0 *model.OrderBook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*model.OrderBook, error)); ok {
		return rf(ctx, symbol, depth)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *model.OrderBook); ok {
		r0 = rf(ctx, symbol, depth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrderBook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, symbol, depth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MEXCClient_GetOrderBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderBook'
type MEXCClient_GetOrderBook_Call struct {
	*mock.Call
}

// GetOrderBook is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - depth int
func (_e *MEXCClient_Expecter) GetOrderBook(ctx interface{}, symbol interface{}, depth interface{}) *MEXCClient_GetOrderBook_Call {
	return &MEXCClient_GetOrderBook_Call{Call: _e.mock.On("GetOrderBook", ctx, symbol, depth)}
}

func (_c *MEXCClient_GetOrderBook_Call) Run(run func(ctx context.Context, symbol string, depth int)) *MEXCClient_GetOrderBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MEXCClient_GetOrderBook_Call) Return(_a0 *model.OrderBook, _a1 error) *MEXCClient_GetOrderBook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MEXCClient_GetOrderBook_Call) RunAndReturn(run func(context.Context, string, int) (*model.OrderBook, error)) *MEXCClient_GetOrderBook_Call {
	_c.Call.Return(run)
	return _c
}

// GetServerTime provides a mock function with given fields: ctx
func (_m *MEXCClient) GetServerTime(ctx context.Context) (time.Time, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetServerTime")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (time.Time, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) time.Time); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MEXCClient_GetServerTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServerTime'
type MEXCClient_GetServerTime_Call struct {
	*mock.Call
}

// GetServerTime is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MEXCClient_Expecter) GetServerTime(ctx interface{}) *MEXCClient_GetServerTime_Call {
	return &MEXCClient_GetServerTime_Call{Call: _e.mock.On("GetServerTime", ctx)}
}

func (_c *MEXCClient_GetServerTime_Call) Run(run func(ctx context.Context)) *MEXCClient_GetServerTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MEXCClient_GetServerTime_Call) Return(_a0 time.Time, _a1 error) *MEXCClient_GetServerTime_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MEXCClient_GetServerTime_Call) RunAndReturn(run func(context.Context) (time.Time, error)) *MEXCClient_GetServerTime_Call {
	_c.Call.Return(run)
	return _c
}

// GetSymbol provides a mock function with given fields: ctx, symbol
func (_m *MEXCClient) GetSymbol(ctx context.Context, symbol string) (*model.Symbol, error) {
	ret := _m.Called(ctx, symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetSymbol")
	}

	var r0 *model.Symbol
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Symbol, error)); ok {
		return rf(ctx, symbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Symbol); ok {
		r0 = rf(ctx, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Symbol)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MEXCClient_GetSymbol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSymbol'
type MEXCClient_GetSymbol_Call struct {
	*mock.Call
}

// GetSymbol is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
func (_e *MEXCClient_Expecter) GetSymbol(ctx interface{}, symbol interface{}) *MEXCClient_GetSymbol_Call {
	return &MEXCClient_GetSymbol_Call{Call: _e.mock.On("GetSymbol", ctx, symbol)}
}

func (_c *MEXCClient_GetSymbol_Call) Run(run func(ctx context.Context, symbol string)) *MEXCClient_GetSymbol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MEXCClient_GetSymbol_Call) Return(_a0 *model.Symbol, _a1 error) *MEXCClient_GetSymbol_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MEXCClient_GetSymbol_Call) RunAndReturn(run func(context.Context, string) (*model.Symbol, error)) *MEXCClient_GetSymbol_Call {
	_c.Call.Return(run)
	return _c
}

// GetSymbols provides a mock function with given fields: ctx
func (_m *MEXCClient) GetSymbols(ctx context.Context) ([]*model.Symbol, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSymbols")
	}

	var r0 []*model.Symbol
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Symbol, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Symbol); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Symbol)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MEXCClient_GetSymbols_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSymbols'
type MEXCClient_GetSymbols_Call struct {
	*mock.Call
}

// GetSymbols is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MEXCClient_Expecter) GetSymbols(ctx interface{}) *MEXCClient_GetSymbols_Call {
	return &MEXCClient_GetSymbols_Call{Call: _e.mock.On("GetSymbols", ctx)}
}

func (_c *MEXCClient_GetSymbols_Call) Run(run func(ctx context.Context)) *MEXCClient_GetSymbols_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MEXCClient_GetSymbols_Call) Return(_a0 []*model.Symbol, _a1 error) *MEXCClient_GetSymbols_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MEXCClient_GetSymbols_Call) RunAndReturn(run func(context.Context) ([]*model.Symbol, error)) *MEXCClient_GetSymbols_Call {
	_c.Call.Return(run)
	return _c
}

// PlaceOrder provides a mock function with given fields: ctx, symbol, side, orderType, quantity, price, timeInForce
func (_m *MEXCClient) PlaceOrder(ctx context.Context, symbol string, side model.OrderSide, orderType model.OrderType, quantity float64, price float64, timeInForce model.TimeInForce) (*model.Order, error) {
	ret := _m.Called(ctx, symbol, side, orderType, quantity, price, timeInForce)

	if len(ret) == 0 {
		panic("no return value specified for PlaceOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.OrderSide, model.OrderType, float64, float64, model.TimeInForce) (*model.Order, error)); ok {
		return rf(ctx, symbol, side, orderType, quantity, price, timeInForce)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.OrderSide, model.OrderType, float64, float64, model.TimeInForce) *model.Order); ok {
		r0 = rf(ctx, symbol, side, orderType, quantity, price, timeInForce)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.OrderSide, model.OrderType, float64, float64, model.TimeInForce) error); ok {
		r1 = rf(ctx, symbol, side, orderType, quantity, price, timeInForce)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MEXCClient_PlaceOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaceOrder'
type MEXCClient_PlaceOrder_Call struct {
	*mock.Call
}

// PlaceOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - side model.OrderSide
//   - orderType model.OrderType
//   - quantity float64
//   - price float64
//   - timeInForce model.TimeInForce
func (_e *MEXCClient_Expecter) PlaceOrder(ctx interface{}, symbol interface{}, side interface{}, orderType interface{}, quantity interface{}, price interface{}, timeInForce interface{}) *MEXCClient_PlaceOrder_Call {
	return &MEXCClient_PlaceOrder_Call{Call: _e.mock.On("PlaceOrder", ctx, symbol, side, orderType, quantity, price, timeInForce)}
}

func (_c *MEXCClient_PlaceOrder_Call) Run(run func(ctx context.Context, symbol string, side model.OrderSide, orderType model.OrderType, quantity float64, price float64, timeInForce model.TimeInForce)) *MEXCClient_PlaceOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.OrderSide), args[3].(model.OrderType), args[4].(float64), args[5].(float64), args[6].(model.TimeInForce))
	})
	return _c
}

func (_c *MEXCClient_PlaceOrder_Call) Return(_a0 *model.Order, _a1 error) *MEXCClient_PlaceOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MEXCClient_PlaceOrder_Call) RunAndReturn(run func(context.Context, string, model.OrderSide, model.OrderType, float64, float64, model.TimeInForce) (*model.Order, error)) *MEXCClient_PlaceOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMEXCClient creates a new instance of MEXCClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMEXCClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MEXCClient {
	mock := &MEXCClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
