// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	port "github.com/RyanLisse/go-crypto-bot-clean/clean_backend/internal/domain/port"
	mock "github.com/stretchr/testify/mock"
)

// RepositoryFactory is an autogenerated mock type for the RepositoryFactory type
type RepositoryFactory struct {
	mock.Mock
}

type RepositoryFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryFactory) EXPECT() *RepositoryFactory_Expecter {
	return &RepositoryFactory_Expecter{mock: &_m.Mock}
}

// CreateAPICredentialRepository provides a mock function with no fields
func (_m *RepositoryFactory) CreateAPICredentialRepository() port.APICredentialRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateAPICredentialRepository")
	}

	var r0 port.APICredentialRepository
	if rf, ok := ret.Get(0).(func() port.APICredentialRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(port.APICredentialRepository)
		}
	}

	return r0
}

// RepositoryFactory_CreateAPICredentialRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAPICredentialRepository'
type RepositoryFactory_CreateAPICredentialRepository_Call struct {
	*mock.Call
}

// CreateAPICredentialRepository is a helper method to define mock.On call
func (_e *RepositoryFactory_Expecter) CreateAPICredentialRepository() *RepositoryFactory_CreateAPICredentialRepository_Call {
	return &RepositoryFactory_CreateAPICredentialRepository_Call{Call: _e.mock.On("CreateAPICredentialRepository")}
}

func (_c *RepositoryFactory_CreateAPICredentialRepository_Call) Run(run func()) *RepositoryFactory_CreateAPICredentialRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryFactory_CreateAPICredentialRepository_Call) Return(_a0 port.APICredentialRepository) *RepositoryFactory_CreateAPICredentialRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryFactory_CreateAPICredentialRepository_Call) RunAndReturn(run func() port.APICredentialRepository) *RepositoryFactory_CreateAPICredentialRepository_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEventRepository provides a mock function with no fields
func (_m *RepositoryFactory) CreateEventRepository() port.EventRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateEventRepository")
	}

	var r0 port.EventRepository
	if rf, ok := ret.Get(0).(func() port.EventRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(port.EventRepository)
		}
	}

	return r0
}

// RepositoryFactory_CreateEventRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEventRepository'
type RepositoryFactory_CreateEventRepository_Call struct {
	*mock.Call
}

// CreateEventRepository is a helper method to define mock.On call
func (_e *RepositoryFactory_Expecter) CreateEventRepository() *RepositoryFactory_CreateEventRepository_Call {
	return &RepositoryFactory_CreateEventRepository_Call{Call: _e.mock.On("CreateEventRepository")}
}

func (_c *RepositoryFactory_CreateEventRepository_Call) Run(run func()) *RepositoryFactory_CreateEventRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryFactory_CreateEventRepository_Call) Return(_a0 port.EventRepository) *RepositoryFactory_CreateEventRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryFactory_CreateEventRepository_Call) RunAndReturn(run func() port.EventRepository) *RepositoryFactory_CreateEventRepository_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMarketRepository provides a mock function with no fields
func (_m *RepositoryFactory) CreateMarketRepository() port.MarketRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateMarketRepository")
	}

	var r0 port.MarketRepository
	if rf, ok := ret.Get(0).(func() port.MarketRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(port.MarketRepository)
		}
	}

	return r0
}

// RepositoryFactory_CreateMarketRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMarketRepository'
type RepositoryFactory_CreateMarketRepository_Call struct {
	*mock.Call
}

// CreateMarketRepository is a helper method to define mock.On call
func (_e *RepositoryFactory_Expecter) CreateMarketRepository() *RepositoryFactory_CreateMarketRepository_Call {
	return &RepositoryFactory_CreateMarketRepository_Call{Call: _e.mock.On("CreateMarketRepository")}
}

func (_c *RepositoryFactory_CreateMarketRepository_Call) Run(run func()) *RepositoryFactory_CreateMarketRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryFactory_CreateMarketRepository_Call) Return(_a0 port.MarketRepository) *RepositoryFactory_CreateMarketRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryFactory_CreateMarketRepository_Call) RunAndReturn(run func() port.MarketRepository) *RepositoryFactory_CreateMarketRepository_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNewCoinRepository provides a mock function with no fields
func (_m *RepositoryFactory) CreateNewCoinRepository() port.NewCoinRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateNewCoinRepository")
	}

	var r0 port.NewCoinRepository
	if rf, ok := ret.Get(0).(func() port.NewCoinRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(port.NewCoinRepository)
		}
	}

	return r0
}

// RepositoryFactory_CreateNewCoinRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNewCoinRepository'
type RepositoryFactory_CreateNewCoinRepository_Call struct {
	*mock.Call
}

// CreateNewCoinRepository is a helper method to define mock.On call
func (_e *RepositoryFactory_Expecter) CreateNewCoinRepository() *RepositoryFactory_CreateNewCoinRepository_Call {
	return &RepositoryFactory_CreateNewCoinRepository_Call{Call: _e.mock.On("CreateNewCoinRepository")}
}

func (_c *RepositoryFactory_CreateNewCoinRepository_Call) Run(run func()) *RepositoryFactory_CreateNewCoinRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryFactory_CreateNewCoinRepository_Call) Return(_a0 port.NewCoinRepository) *RepositoryFactory_CreateNewCoinRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryFactory_CreateNewCoinRepository_Call) RunAndReturn(run func() port.NewCoinRepository) *RepositoryFactory_CreateNewCoinRepository_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrderRepository provides a mock function with no fields
func (_m *RepositoryFactory) CreateOrderRepository() port.OrderRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateOrderRepository")
	}

	var r0 port.OrderRepository
	if rf, ok := ret.Get(0).(func() port.OrderRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(port.OrderRepository)
		}
	}

	return r0
}

// RepositoryFactory_CreateOrderRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrderRepository'
type RepositoryFactory_CreateOrderRepository_Call struct {
	*mock.Call
}

// CreateOrderRepository is a helper method to define mock.On call
func (_e *RepositoryFactory_Expecter) CreateOrderRepository() *RepositoryFactory_CreateOrderRepository_Call {
	return &RepositoryFactory_CreateOrderRepository_Call{Call: _e.mock.On("CreateOrderRepository")}
}

func (_c *RepositoryFactory_CreateOrderRepository_Call) Run(run func()) *RepositoryFactory_CreateOrderRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryFactory_CreateOrderRepository_Call) Return(_a0 port.OrderRepository) *RepositoryFactory_CreateOrderRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryFactory_CreateOrderRepository_Call) RunAndReturn(run func() port.OrderRepository) *RepositoryFactory_CreateOrderRepository_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSymbolRepository provides a mock function with no fields
func (_m *RepositoryFactory) CreateSymbolRepository() port.SymbolRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateSymbolRepository")
	}

	var r0 port.SymbolRepository
	if rf, ok := ret.Get(0).(func() port.SymbolRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(port.SymbolRepository)
		}
	}

	return r0
}

// RepositoryFactory_CreateSymbolRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSymbolRepository'
type RepositoryFactory_CreateSymbolRepository_Call struct {
	*mock.Call
}

// CreateSymbolRepository is a helper method to define mock.On call
func (_e *RepositoryFactory_Expecter) CreateSymbolRepository() *RepositoryFactory_CreateSymbolRepository_Call {
	return &RepositoryFactory_CreateSymbolRepository_Call{Call: _e.mock.On("CreateSymbolRepository")}
}

func (_c *RepositoryFactory_CreateSymbolRepository_Call) Run(run func()) *RepositoryFactory_CreateSymbolRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryFactory_CreateSymbolRepository_Call) Return(_a0 port.SymbolRepository) *RepositoryFactory_CreateSymbolRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryFactory_CreateSymbolRepository_Call) RunAndReturn(run func() port.SymbolRepository) *RepositoryFactory_CreateSymbolRepository_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserRepository provides a mock function with no fields
func (_m *RepositoryFactory) CreateUserRepository() port.UserRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateUserRepository")
	}

	var r0 port.UserRepository
	if rf, ok := ret.Get(0).(func() port.UserRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(port.UserRepository)
		}
	}

	return r0
}

// RepositoryFactory_CreateUserRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserRepository'
type RepositoryFactory_CreateUserRepository_Call struct {
	*mock.Call
}

// CreateUserRepository is a helper method to define mock.On call
func (_e *RepositoryFactory_Expecter) CreateUserRepository() *RepositoryFactory_CreateUserRepository_Call {
	return &RepositoryFactory_CreateUserRepository_Call{Call: _e.mock.On("CreateUserRepository")}
}

func (_c *RepositoryFactory_CreateUserRepository_Call) Run(run func()) *RepositoryFactory_CreateUserRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryFactory_CreateUserRepository_Call) Return(_a0 port.UserRepository) *RepositoryFactory_CreateUserRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryFactory_CreateUserRepository_Call) RunAndReturn(run func() port.UserRepository) *RepositoryFactory_CreateUserRepository_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWalletRepository provides a mock function with no fields
func (_m *RepositoryFactory) CreateWalletRepository() port.WalletRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateWalletRepository")
	}

	var r0 port.WalletRepository
	if rf, ok := ret.Get(0).(func() port.WalletRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(port.WalletRepository)
		}
	}

	return r0
}

// RepositoryFactory_CreateWalletRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWalletRepository'
type RepositoryFactory_CreateWalletRepository_Call struct {
	*mock.Call
}

// CreateWalletRepository is a helper method to define mock.On call
func (_e *RepositoryFactory_Expecter) CreateWalletRepository() *RepositoryFactory_CreateWalletRepository_Call {
	return &RepositoryFactory_CreateWalletRepository_Call{Call: _e.mock.On("CreateWalletRepository")}
}

func (_c *RepositoryFactory_CreateWalletRepository_Call) Run(run func()) *RepositoryFactory_CreateWalletRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryFactory_CreateWalletRepository_Call) Return(_a0 port.WalletRepository) *RepositoryFactory_CreateWalletRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryFactory_CreateWalletRepository_Call) RunAndReturn(run func() port.WalletRepository) *RepositoryFactory_CreateWalletRepository_Call {
	_c.Call.Return(run)
	return _c
}

// WithEncryptionService provides a mock function with given fields: encryptionSvc
func (_m *RepositoryFactory) WithEncryptionService(encryptionSvc port.EncryptionService) port.RepositoryFactory {
	ret := _m.Called(encryptionSvc)

	if len(ret) == 0 {
		panic("no return value specified for WithEncryptionService")
	}

	var r0 port.RepositoryFactory
	if rf, ok := ret.Get(0).(func(port.EncryptionService) port.RepositoryFactory); ok {
		r0 = rf(encryptionSvc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(port.RepositoryFactory)
		}
	}

	return r0
}

// RepositoryFactory_WithEncryptionService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithEncryptionService'
type RepositoryFactory_WithEncryptionService_Call struct {
	*mock.Call
}

// WithEncryptionService is a helper method to define mock.On call
//   - encryptionSvc port.EncryptionService
func (_e *RepositoryFactory_Expecter) WithEncryptionService(encryptionSvc interface{}) *RepositoryFactory_WithEncryptionService_Call {
	return &RepositoryFactory_WithEncryptionService_Call{Call: _e.mock.On("WithEncryptionService", encryptionSvc)}
}

func (_c *RepositoryFactory_WithEncryptionService_Call) Run(run func(encryptionSvc port.EncryptionService)) *RepositoryFactory_WithEncryptionService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(port.EncryptionService))
	})
	return _c
}

func (_c *RepositoryFactory_WithEncryptionService_Call) Return(_a0 port.RepositoryFactory) *RepositoryFactory_WithEncryptionService_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryFactory_WithEncryptionService_Call) RunAndReturn(run func(port.EncryptionService) port.RepositoryFactory) *RepositoryFactory_WithEncryptionService_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositoryFactory creates a new instance of RepositoryFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryFactory {
	mock := &RepositoryFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
