// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/RyanLisse/go-crypto-bot-clean/clean_backend/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// RiskParameterRepository is an autogenerated mock type for the RiskParameterRepository type
type RiskParameterRepository struct {
	mock.Mock
}

type RiskParameterRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RiskParameterRepository) EXPECT() *RiskParameterRepository_Expecter {
	return &RiskParameterRepository_Expecter{mock: &_m.Mock}
}

// GetParameters provides a mock function with given fields: ctx, userID
func (_m *RiskParameterRepository) GetParameters(ctx context.Context, userID string) (*model.RiskParameters, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetParameters")
	}

	var r0 *model.RiskParameters
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.RiskParameters, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.RiskParameters); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RiskParameters)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RiskParameterRepository_GetParameters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParameters'
type RiskParameterRepository_GetParameters_Call struct {
	*mock.Call
}

// GetParameters is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *RiskParameterRepository_Expecter) GetParameters(ctx interface{}, userID interface{}) *RiskParameterRepository_GetParameters_Call {
	return &RiskParameterRepository_GetParameters_Call{Call: _e.mock.On("GetParameters", ctx, userID)}
}

func (_c *RiskParameterRepository_GetParameters_Call) Run(run func(ctx context.Context, userID string)) *RiskParameterRepository_GetParameters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RiskParameterRepository_GetParameters_Call) Return(_a0 *model.RiskParameters, _a1 error) *RiskParameterRepository_GetParameters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RiskParameterRepository_GetParameters_Call) RunAndReturn(run func(context.Context, string) (*model.RiskParameters, error)) *RiskParameterRepository_GetParameters_Call {
	_c.Call.Return(run)
	return _c
}

// SaveParameters provides a mock function with given fields: ctx, params
func (_m *RiskParameterRepository) SaveParameters(ctx context.Context, params *model.RiskParameters) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SaveParameters")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RiskParameters) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RiskParameterRepository_SaveParameters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveParameters'
type RiskParameterRepository_SaveParameters_Call struct {
	*mock.Call
}

// SaveParameters is a helper method to define mock.On call
//   - ctx context.Context
//   - params *model.RiskParameters
func (_e *RiskParameterRepository_Expecter) SaveParameters(ctx interface{}, params interface{}) *RiskParameterRepository_SaveParameters_Call {
	return &RiskParameterRepository_SaveParameters_Call{Call: _e.mock.On("SaveParameters", ctx, params)}
}

func (_c *RiskParameterRepository_SaveParameters_Call) Run(run func(ctx context.Context, params *model.RiskParameters)) *RiskParameterRepository_SaveParameters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.RiskParameters))
	})
	return _c
}

func (_c *RiskParameterRepository_SaveParameters_Call) Return(_a0 error) *RiskParameterRepository_SaveParameters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RiskParameterRepository_SaveParameters_Call) RunAndReturn(run func(context.Context, *model.RiskParameters) error) *RiskParameterRepository_SaveParameters_Call {
	_c.Call.Return(run)
	return _c
}

// NewRiskParameterRepository creates a new instance of RiskParameterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRiskParameterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RiskParameterRepository {
	mock := &RiskParameterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
