// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/RyanLisse/go-crypto-bot-clean/clean_backend/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RiskAssessmentRepository is an autogenerated mock type for the RiskAssessmentRepository type
type RiskAssessmentRepository struct {
	mock.Mock
}

type RiskAssessmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RiskAssessmentRepository) EXPECT() *RiskAssessmentRepository_Expecter {
	return &RiskAssessmentRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: ctx, filters
func (_m *RiskAssessmentRepository) Count(ctx context.Context, filters map[string]interface{}) (int64, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) (int64, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) int64); ok {
		r0 = rf(ctx, filters)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RiskAssessmentRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type RiskAssessmentRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - filters map[string]interface{}
func (_e *RiskAssessmentRepository_Expecter) Count(ctx interface{}, filters interface{}) *RiskAssessmentRepository_Count_Call {
	return &RiskAssessmentRepository_Count_Call{Call: _e.mock.On("Count", ctx, filters)}
}

func (_c *RiskAssessmentRepository_Count_Call) Run(run func(ctx context.Context, filters map[string]interface{})) *RiskAssessmentRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]interface{}))
	})
	return _c
}

func (_c *RiskAssessmentRepository_Count_Call) Return(_a0 int64, _a1 error) *RiskAssessmentRepository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RiskAssessmentRepository_Count_Call) RunAndReturn(run func(context.Context, map[string]interface{}) (int64, error)) *RiskAssessmentRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, assessment
func (_m *RiskAssessmentRepository) Create(ctx context.Context, assessment *model.RiskAssessment) error {
	ret := _m.Called(ctx, assessment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RiskAssessment) error); ok {
		r0 = rf(ctx, assessment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RiskAssessmentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RiskAssessmentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - assessment *model.RiskAssessment
func (_e *RiskAssessmentRepository_Expecter) Create(ctx interface{}, assessment interface{}) *RiskAssessmentRepository_Create_Call {
	return &RiskAssessmentRepository_Create_Call{Call: _e.mock.On("Create", ctx, assessment)}
}

func (_c *RiskAssessmentRepository_Create_Call) Run(run func(ctx context.Context, assessment *model.RiskAssessment)) *RiskAssessmentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.RiskAssessment))
	})
	return _c
}

func (_c *RiskAssessmentRepository_Create_Call) Return(_a0 error) *RiskAssessmentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RiskAssessmentRepository_Create_Call) RunAndReturn(run func(context.Context, *model.RiskAssessment) error) *RiskAssessmentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *RiskAssessmentRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RiskAssessmentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RiskAssessmentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *RiskAssessmentRepository_Expecter) Delete(ctx interface{}, id interface{}) *RiskAssessmentRepository_Delete_Call {
	return &RiskAssessmentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *RiskAssessmentRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *RiskAssessmentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RiskAssessmentRepository_Delete_Call) Return(_a0 error) *RiskAssessmentRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RiskAssessmentRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *RiskAssessmentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveByUserID provides a mock function with given fields: ctx, userID
func (_m *RiskAssessmentRepository) GetActiveByUserID(ctx context.Context, userID string) ([]*model.RiskAssessment, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByUserID")
	}

	var r0 []*model.RiskAssessment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.RiskAssessment, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.RiskAssessment); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.RiskAssessment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RiskAssessmentRepository_GetActiveByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveByUserID'
type RiskAssessmentRepository_GetActiveByUserID_Call struct {
	*mock.Call
}

// GetActiveByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *RiskAssessmentRepository_Expecter) GetActiveByUserID(ctx interface{}, userID interface{}) *RiskAssessmentRepository_GetActiveByUserID_Call {
	return &RiskAssessmentRepository_GetActiveByUserID_Call{Call: _e.mock.On("GetActiveByUserID", ctx, userID)}
}

func (_c *RiskAssessmentRepository_GetActiveByUserID_Call) Run(run func(ctx context.Context, userID string)) *RiskAssessmentRepository_GetActiveByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RiskAssessmentRepository_GetActiveByUserID_Call) Return(_a0 []*model.RiskAssessment, _a1 error) *RiskAssessmentRepository_GetActiveByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RiskAssessmentRepository_GetActiveByUserID_Call) RunAndReturn(run func(context.Context, string) ([]*model.RiskAssessment, error)) *RiskAssessmentRepository_GetActiveByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *RiskAssessmentRepository) GetByID(ctx context.Context, id string) (*model.RiskAssessment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.RiskAssessment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.RiskAssessment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.RiskAssessment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RiskAssessment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RiskAssessmentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type RiskAssessmentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *RiskAssessmentRepository_Expecter) GetByID(ctx interface{}, id interface{}) *RiskAssessmentRepository_GetByID_Call {
	return &RiskAssessmentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *RiskAssessmentRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *RiskAssessmentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RiskAssessmentRepository_GetByID_Call) Return(_a0 *model.RiskAssessment, _a1 error) *RiskAssessmentRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RiskAssessmentRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*model.RiskAssessment, error)) *RiskAssessmentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLevel provides a mock function with given fields: ctx, level, limit, offset
func (_m *RiskAssessmentRepository) GetByLevel(ctx context.Context, level model.RiskLevel, limit int, offset int) ([]*model.RiskAssessment, error) {
	ret := _m.Called(ctx, level, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByLevel")
	}

	var r0 []*model.RiskAssessment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.RiskLevel, int, int) ([]*model.RiskAssessment, error)); ok {
		return rf(ctx, level, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.RiskLevel, int, int) []*model.RiskAssessment); ok {
		r0 = rf(ctx, level, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.RiskAssessment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.RiskLevel, int, int) error); ok {
		r1 = rf(ctx, level, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RiskAssessmentRepository_GetByLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLevel'
type RiskAssessmentRepository_GetByLevel_Call struct {
	*mock.Call
}

// GetByLevel is a helper method to define mock.On call
//   - ctx context.Context
//   - level model.RiskLevel
//   - limit int
//   - offset int
func (_e *RiskAssessmentRepository_Expecter) GetByLevel(ctx interface{}, level interface{}, limit interface{}, offset interface{}) *RiskAssessmentRepository_GetByLevel_Call {
	return &RiskAssessmentRepository_GetByLevel_Call{Call: _e.mock.On("GetByLevel", ctx, level, limit, offset)}
}

func (_c *RiskAssessmentRepository_GetByLevel_Call) Run(run func(ctx context.Context, level model.RiskLevel, limit int, offset int)) *RiskAssessmentRepository_GetByLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.RiskLevel), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *RiskAssessmentRepository_GetByLevel_Call) Return(_a0 []*model.RiskAssessment, _a1 error) *RiskAssessmentRepository_GetByLevel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RiskAssessmentRepository_GetByLevel_Call) RunAndReturn(run func(context.Context, model.RiskLevel, int, int) ([]*model.RiskAssessment, error)) *RiskAssessmentRepository_GetByLevel_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySymbol provides a mock function with given fields: ctx, symbol, limit, offset
func (_m *RiskAssessmentRepository) GetBySymbol(ctx context.Context, symbol string, limit int, offset int) ([]*model.RiskAssessment, error) {
	ret := _m.Called(ctx, symbol, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetBySymbol")
	}

	var r0 []*model.RiskAssessment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*model.RiskAssessment, error)); ok {
		return rf(ctx, symbol, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*model.RiskAssessment); ok {
		r0 = rf(ctx, symbol, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.RiskAssessment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, symbol, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RiskAssessmentRepository_GetBySymbol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySymbol'
type RiskAssessmentRepository_GetBySymbol_Call struct {
	*mock.Call
}

// GetBySymbol is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - limit int
//   - offset int
func (_e *RiskAssessmentRepository_Expecter) GetBySymbol(ctx interface{}, symbol interface{}, limit interface{}, offset interface{}) *RiskAssessmentRepository_GetBySymbol_Call {
	return &RiskAssessmentRepository_GetBySymbol_Call{Call: _e.mock.On("GetBySymbol", ctx, symbol, limit, offset)}
}

func (_c *RiskAssessmentRepository_GetBySymbol_Call) Run(run func(ctx context.Context, symbol string, limit int, offset int)) *RiskAssessmentRepository_GetBySymbol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *RiskAssessmentRepository_GetBySymbol_Call) Return(_a0 []*model.RiskAssessment, _a1 error) *RiskAssessmentRepository_GetBySymbol_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RiskAssessmentRepository_GetBySymbol_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*model.RiskAssessment, error)) *RiskAssessmentRepository_GetBySymbol_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTimeRange provides a mock function with given fields: ctx, from, to, limit, offset
func (_m *RiskAssessmentRepository) GetByTimeRange(ctx context.Context, from time.Time, to time.Time, limit int, offset int) ([]*model.RiskAssessment, error) {
	ret := _m.Called(ctx, from, to, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByTimeRange")
	}

	var r0 []*model.RiskAssessment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) ([]*model.RiskAssessment, error)); ok {
		return rf(ctx, from, to, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) []*model.RiskAssessment); ok {
		r0 = rf(ctx, from, to, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.RiskAssessment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, int, int) error); ok {
		r1 = rf(ctx, from, to, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RiskAssessmentRepository_GetByTimeRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTimeRange'
type RiskAssessmentRepository_GetByTimeRange_Call struct {
	*mock.Call
}

// GetByTimeRange is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
//   - limit int
//   - offset int
func (_e *RiskAssessmentRepository_Expecter) GetByTimeRange(ctx interface{}, from interface{}, to interface{}, limit interface{}, offset interface{}) *RiskAssessmentRepository_GetByTimeRange_Call {
	return &RiskAssessmentRepository_GetByTimeRange_Call{Call: _e.mock.On("GetByTimeRange", ctx, from, to, limit, offset)}
}

func (_c *RiskAssessmentRepository_GetByTimeRange_Call) Run(run func(ctx context.Context, from time.Time, to time.Time, limit int, offset int)) *RiskAssessmentRepository_GetByTimeRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *RiskAssessmentRepository_GetByTimeRange_Call) Return(_a0 []*model.RiskAssessment, _a1 error) *RiskAssessmentRepository_GetByTimeRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RiskAssessmentRepository_GetByTimeRange_Call) RunAndReturn(run func(context.Context, time.Time, time.Time, int, int) ([]*model.RiskAssessment, error)) *RiskAssessmentRepository_GetByTimeRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetByType provides a mock function with given fields: ctx, riskType, limit, offset
func (_m *RiskAssessmentRepository) GetByType(ctx context.Context, riskType model.RiskType, limit int, offset int) ([]*model.RiskAssessment, error) {
	ret := _m.Called(ctx, riskType, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByType")
	}

	var r0 []*model.RiskAssessment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.RiskType, int, int) ([]*model.RiskAssessment, error)); ok {
		return rf(ctx, riskType, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.RiskType, int, int) []*model.RiskAssessment); ok {
		r0 = rf(ctx, riskType, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.RiskAssessment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.RiskType, int, int) error); ok {
		r1 = rf(ctx, riskType, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RiskAssessmentRepository_GetByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByType'
type RiskAssessmentRepository_GetByType_Call struct {
	*mock.Call
}

// GetByType is a helper method to define mock.On call
//   - ctx context.Context
//   - riskType model.RiskType
//   - limit int
//   - offset int
func (_e *RiskAssessmentRepository_Expecter) GetByType(ctx interface{}, riskType interface{}, limit interface{}, offset interface{}) *RiskAssessmentRepository_GetByType_Call {
	return &RiskAssessmentRepository_GetByType_Call{Call: _e.mock.On("GetByType", ctx, riskType, limit, offset)}
}

func (_c *RiskAssessmentRepository_GetByType_Call) Run(run func(ctx context.Context, riskType model.RiskType, limit int, offset int)) *RiskAssessmentRepository_GetByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.RiskType), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *RiskAssessmentRepository_GetByType_Call) Return(_a0 []*model.RiskAssessment, _a1 error) *RiskAssessmentRepository_GetByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RiskAssessmentRepository_GetByType_Call) RunAndReturn(run func(context.Context, model.RiskType, int, int) ([]*model.RiskAssessment, error)) *RiskAssessmentRepository_GetByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID, limit, offset
func (_m *RiskAssessmentRepository) GetByUserID(ctx context.Context, userID string, limit int, offset int) ([]*model.RiskAssessment, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*model.RiskAssessment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*model.RiskAssessment, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*model.RiskAssessment); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.RiskAssessment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RiskAssessmentRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type RiskAssessmentRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
func (_e *RiskAssessmentRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *RiskAssessmentRepository_GetByUserID_Call {
	return &RiskAssessmentRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID, limit, offset)}
}

func (_c *RiskAssessmentRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID string, limit int, offset int)) *RiskAssessmentRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *RiskAssessmentRepository_GetByUserID_Call) Return(_a0 []*model.RiskAssessment, _a1 error) *RiskAssessmentRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RiskAssessmentRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*model.RiskAssessment, error)) *RiskAssessmentRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, assessment
func (_m *RiskAssessmentRepository) Update(ctx context.Context, assessment *model.RiskAssessment) error {
	ret := _m.Called(ctx, assessment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RiskAssessment) error); ok {
		r0 = rf(ctx, assessment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RiskAssessmentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type RiskAssessmentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - assessment *model.RiskAssessment
func (_e *RiskAssessmentRepository_Expecter) Update(ctx interface{}, assessment interface{}) *RiskAssessmentRepository_Update_Call {
	return &RiskAssessmentRepository_Update_Call{Call: _e.mock.On("Update", ctx, assessment)}
}

func (_c *RiskAssessmentRepository_Update_Call) Run(run func(ctx context.Context, assessment *model.RiskAssessment)) *RiskAssessmentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.RiskAssessment))
	})
	return _c
}

func (_c *RiskAssessmentRepository_Update_Call) Return(_a0 error) *RiskAssessmentRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RiskAssessmentRepository_Update_Call) RunAndReturn(run func(context.Context, *model.RiskAssessment) error) *RiskAssessmentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRiskAssessmentRepository creates a new instance of RiskAssessmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRiskAssessmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RiskAssessmentRepository {
	mock := &RiskAssessmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
