// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SymbolProvider is an autogenerated mock type for the SymbolProvider type
type SymbolProvider struct {
	mock.Mock
}

type SymbolProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *SymbolProvider) EXPECT() *SymbolProvider_Expecter {
	return &SymbolProvider_Expecter{mock: &_m.Mock}
}

// NewSymbolProvider creates a new instance of SymbolProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSymbolProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *SymbolProvider {
	mock := &SymbolProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
