// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/RyanLisse/go-crypto-bot-clean/clean_backend/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// TradeExecutor is an autogenerated mock type for the TradeExecutor type
type TradeExecutor struct {
	mock.Mock
}

type TradeExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *TradeExecutor) EXPECT() *TradeExecutor_Expecter {
	return &TradeExecutor_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, symbol, orderID
func (_m *TradeExecutor) CancelOrder(ctx context.Context, symbol string, orderID string) error {
	ret := _m.Called(ctx, symbol, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, symbol, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TradeExecutor_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type TradeExecutor_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - orderID string
func (_e *TradeExecutor_Expecter) CancelOrder(ctx interface{}, symbol interface{}, orderID interface{}) *TradeExecutor_CancelOrder_Call {
	return &TradeExecutor_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, symbol, orderID)}
}

func (_c *TradeExecutor_CancelOrder_Call) Run(run func(ctx context.Context, symbol string, orderID string)) *TradeExecutor_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TradeExecutor_CancelOrder_Call) Return(_a0 error) *TradeExecutor_CancelOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TradeExecutor_CancelOrder_Call) RunAndReturn(run func(context.Context, string, string) error) *TradeExecutor_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CancelOrderWithRetry provides a mock function with given fields: ctx, symbol, orderID
func (_m *TradeExecutor) CancelOrderWithRetry(ctx context.Context, symbol string, orderID string) error {
	ret := _m.Called(ctx, symbol, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrderWithRetry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, symbol, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TradeExecutor_CancelOrderWithRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrderWithRetry'
type TradeExecutor_CancelOrderWithRetry_Call struct {
	*mock.Call
}

// CancelOrderWithRetry is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - orderID string
func (_e *TradeExecutor_Expecter) CancelOrderWithRetry(ctx interface{}, symbol interface{}, orderID interface{}) *TradeExecutor_CancelOrderWithRetry_Call {
	return &TradeExecutor_CancelOrderWithRetry_Call{Call: _e.mock.On("CancelOrderWithRetry", ctx, symbol, orderID)}
}

func (_c *TradeExecutor_CancelOrderWithRetry_Call) Run(run func(ctx context.Context, symbol string, orderID string)) *TradeExecutor_CancelOrderWithRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TradeExecutor_CancelOrderWithRetry_Call) Return(_a0 error) *TradeExecutor_CancelOrderWithRetry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TradeExecutor_CancelOrderWithRetry_Call) RunAndReturn(run func(context.Context, string, string) error) *TradeExecutor_CancelOrderWithRetry_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteOrder provides a mock function with given fields: ctx, order
func (_m *TradeExecutor) ExecuteOrder(ctx context.Context, order *model.OrderRequest) (*model.PlaceOrderResponse, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteOrder")
	}

	var r0 *model.PlaceOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.OrderRequest) (*model.PlaceOrderResponse, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.OrderRequest) *model.PlaceOrderResponse); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PlaceOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.OrderRequest) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TradeExecutor_ExecuteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteOrder'
type TradeExecutor_ExecuteOrder_Call struct {
	*mock.Call
}

// ExecuteOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.OrderRequest
func (_e *TradeExecutor_Expecter) ExecuteOrder(ctx interface{}, order interface{}) *TradeExecutor_ExecuteOrder_Call {
	return &TradeExecutor_ExecuteOrder_Call{Call: _e.mock.On("ExecuteOrder", ctx, order)}
}

func (_c *TradeExecutor_ExecuteOrder_Call) Run(run func(ctx context.Context, order *model.OrderRequest)) *TradeExecutor_ExecuteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.OrderRequest))
	})
	return _c
}

func (_c *TradeExecutor_ExecuteOrder_Call) Return(_a0 *model.PlaceOrderResponse, _a1 error) *TradeExecutor_ExecuteOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TradeExecutor_ExecuteOrder_Call) RunAndReturn(run func(context.Context, *model.OrderRequest) (*model.PlaceOrderResponse, error)) *TradeExecutor_ExecuteOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderStatus provides a mock function with given fields: ctx, symbol, orderID
func (_m *TradeExecutor) GetOrderStatus(ctx context.Context, symbol string, orderID string) (*model.Order, error) {
	ret := _m.Called(ctx, symbol, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderStatus")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Order, error)); ok {
		return rf(ctx, symbol, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Order); ok {
		r0 = rf(ctx, symbol, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, symbol, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TradeExecutor_GetOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderStatus'
type TradeExecutor_GetOrderStatus_Call struct {
	*mock.Call
}

// GetOrderStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - orderID string
func (_e *TradeExecutor_Expecter) GetOrderStatus(ctx interface{}, symbol interface{}, orderID interface{}) *TradeExecutor_GetOrderStatus_Call {
	return &TradeExecutor_GetOrderStatus_Call{Call: _e.mock.On("GetOrderStatus", ctx, symbol, orderID)}
}

func (_c *TradeExecutor_GetOrderStatus_Call) Run(run func(ctx context.Context, symbol string, orderID string)) *TradeExecutor_GetOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TradeExecutor_GetOrderStatus_Call) Return(_a0 *model.Order, _a1 error) *TradeExecutor_GetOrderStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TradeExecutor_GetOrderStatus_Call) RunAndReturn(run func(context.Context, string, string) (*model.Order, error)) *TradeExecutor_GetOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderStatusWithRetry provides a mock function with given fields: ctx, symbol, orderID
func (_m *TradeExecutor) GetOrderStatusWithRetry(ctx context.Context, symbol string, orderID string) (*model.Order, error) {
	ret := _m.Called(ctx, symbol, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderStatusWithRetry")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Order, error)); ok {
		return rf(ctx, symbol, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Order); ok {
		r0 = rf(ctx, symbol, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, symbol, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TradeExecutor_GetOrderStatusWithRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderStatusWithRetry'
type TradeExecutor_GetOrderStatusWithRetry_Call struct {
	*mock.Call
}

// GetOrderStatusWithRetry is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - orderID string
func (_e *TradeExecutor_Expecter) GetOrderStatusWithRetry(ctx interface{}, symbol interface{}, orderID interface{}) *TradeExecutor_GetOrderStatusWithRetry_Call {
	return &TradeExecutor_GetOrderStatusWithRetry_Call{Call: _e.mock.On("GetOrderStatusWithRetry", ctx, symbol, orderID)}
}

func (_c *TradeExecutor_GetOrderStatusWithRetry_Call) Run(run func(ctx context.Context, symbol string, orderID string)) *TradeExecutor_GetOrderStatusWithRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TradeExecutor_GetOrderStatusWithRetry_Call) Return(_a0 *model.Order, _a1 error) *TradeExecutor_GetOrderStatusWithRetry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TradeExecutor_GetOrderStatusWithRetry_Call) RunAndReturn(run func(context.Context, string, string) (*model.Order, error)) *TradeExecutor_GetOrderStatusWithRetry_Call {
	_c.Call.Return(run)
	return _c
}

// NewTradeExecutor creates a new instance of TradeExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTradeExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *TradeExecutor {
	mock := &TradeExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
