// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/RyanLisse/go-crypto-bot-clean/clean_backend/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// UserServiceInterface is an autogenerated mock type for the UserServiceInterface type
type UserServiceInterface struct {
	mock.Mock
}

type UserServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *UserServiceInterface) EXPECT() *UserServiceInterface_Expecter {
	return &UserServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *UserServiceInterface) CreateUser(ctx context.Context, user *model.User) (*model.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) (*model.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) *model.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserServiceInterface_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserServiceInterface_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *UserServiceInterface_Expecter) CreateUser(ctx interface{}, user interface{}) *UserServiceInterface_CreateUser_Call {
	return &UserServiceInterface_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *UserServiceInterface_CreateUser_Call) Run(run func(ctx context.Context, user *model.User)) *UserServiceInterface_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User))
	})
	return _c
}

func (_c *UserServiceInterface_CreateUser_Call) Return(_a0 *model.User, _a1 error) *UserServiceInterface_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserServiceInterface_CreateUser_Call) RunAndReturn(run func(context.Context, *model.User) (*model.User, error)) *UserServiceInterface_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, userID
func (_m *UserServiceInterface) DeleteUser(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserServiceInterface_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type UserServiceInterface_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserServiceInterface_Expecter) DeleteUser(ctx interface{}, userID interface{}) *UserServiceInterface_DeleteUser_Call {
	return &UserServiceInterface_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, userID)}
}

func (_c *UserServiceInterface_DeleteUser_Call) Run(run func(ctx context.Context, userID string)) *UserServiceInterface_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserServiceInterface_DeleteUser_Call) Return(_a0 error) *UserServiceInterface_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserServiceInterface_DeleteUser_Call) RunAndReturn(run func(context.Context, string) error) *UserServiceInterface_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *UserServiceInterface) GetUserByEmail(ctx context.Context, email string) (*model.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserServiceInterface_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type UserServiceInterface_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserServiceInterface_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *UserServiceInterface_GetUserByEmail_Call {
	return &UserServiceInterface_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *UserServiceInterface_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *UserServiceInterface_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserServiceInterface_GetUserByEmail_Call) Return(_a0 *model.User, _a1 error) *UserServiceInterface_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserServiceInterface_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *UserServiceInterface_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *UserServiceInterface) GetUserByID(ctx context.Context, userID string) (*model.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserServiceInterface_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type UserServiceInterface_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserServiceInterface_Expecter) GetUserByID(ctx interface{}, userID interface{}) *UserServiceInterface_GetUserByID_Call {
	return &UserServiceInterface_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *UserServiceInterface_GetUserByID_Call) Run(run func(ctx context.Context, userID string)) *UserServiceInterface_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserServiceInterface_GetUserByID_Call) Return(_a0 *model.User, _a1 error) *UserServiceInterface_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserServiceInterface_GetUserByID_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *UserServiceInterface_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx
func (_m *UserServiceInterface) ListUsers(ctx context.Context) ([]*model.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []*model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserServiceInterface_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type UserServiceInterface_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserServiceInterface_Expecter) ListUsers(ctx interface{}) *UserServiceInterface_ListUsers_Call {
	return &UserServiceInterface_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx)}
}

func (_c *UserServiceInterface_ListUsers_Call) Run(run func(ctx context.Context)) *UserServiceInterface_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UserServiceInterface_ListUsers_Call) Return(_a0 []*model.User, _a1 error) *UserServiceInterface_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserServiceInterface_ListUsers_Call) RunAndReturn(run func(context.Context) ([]*model.User, error)) *UserServiceInterface_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUserRole provides a mock function with given fields: ctx, userID, role
func (_m *UserServiceInterface) RemoveUserRole(ctx context.Context, userID string, role string) error {
	ret := _m.Called(ctx, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserServiceInterface_RemoveUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUserRole'
type UserServiceInterface_RemoveUserRole_Call struct {
	*mock.Call
}

// RemoveUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - role string
func (_e *UserServiceInterface_Expecter) RemoveUserRole(ctx interface{}, userID interface{}, role interface{}) *UserServiceInterface_RemoveUserRole_Call {
	return &UserServiceInterface_RemoveUserRole_Call{Call: _e.mock.On("RemoveUserRole", ctx, userID, role)}
}

func (_c *UserServiceInterface_RemoveUserRole_Call) Run(run func(ctx context.Context, userID string, role string)) *UserServiceInterface_RemoveUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserServiceInterface_RemoveUserRole_Call) Return(_a0 error) *UserServiceInterface_RemoveUserRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserServiceInterface_RemoveUserRole_Call) RunAndReturn(run func(context.Context, string, string) error) *UserServiceInterface_RemoveUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserRole provides a mock function with given fields: ctx, userID, role
func (_m *UserServiceInterface) SetUserRole(ctx context.Context, userID string, role string) error {
	ret := _m.Called(ctx, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for SetUserRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserServiceInterface_SetUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserRole'
type UserServiceInterface_SetUserRole_Call struct {
	*mock.Call
}

// SetUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - role string
func (_e *UserServiceInterface_Expecter) SetUserRole(ctx interface{}, userID interface{}, role interface{}) *UserServiceInterface_SetUserRole_Call {
	return &UserServiceInterface_SetUserRole_Call{Call: _e.mock.On("SetUserRole", ctx, userID, role)}
}

func (_c *UserServiceInterface_SetUserRole_Call) Run(run func(ctx context.Context, userID string, role string)) *UserServiceInterface_SetUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserServiceInterface_SetUserRole_Call) Return(_a0 error) *UserServiceInterface_SetUserRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserServiceInterface_SetUserRole_Call) RunAndReturn(run func(context.Context, string, string) error) *UserServiceInterface_SetUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, user
func (_m *UserServiceInterface) UpdateUser(ctx context.Context, user *model.User) (*model.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) (*model.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) *model.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserServiceInterface_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type UserServiceInterface_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *UserServiceInterface_Expecter) UpdateUser(ctx interface{}, user interface{}) *UserServiceInterface_UpdateUser_Call {
	return &UserServiceInterface_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, user)}
}

func (_c *UserServiceInterface_UpdateUser_Call) Run(run func(ctx context.Context, user *model.User)) *UserServiceInterface_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User))
	})
	return _c
}

func (_c *UserServiceInterface_UpdateUser_Call) Return(_a0 *model.User, _a1 error) *UserServiceInterface_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserServiceInterface_UpdateUser_Call) RunAndReturn(run func(context.Context, *model.User) (*model.User, error)) *UserServiceInterface_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserServiceInterface creates a new instance of UserServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserServiceInterface {
	mock := &UserServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
