mexc:
  apiKey: ${MEXC_API_KEY}
  secretKey: ${MEXC_SECRET_KEY}
  baseURL: ${MEXC_BASE_URL}
  wsURL: ${MEXC_WEBSOCKET_URL}

connectionRateLimiter:
  requestsPerSecond: 10
  burstCapacity: 20

subscriptionRateLimiter:
  requestsPerSecond: 5
  burstCapacity: 10

logging:
  level: "debug"
  format: "json"
  output: "stdout"
