[project]
name = "go-crypto-bot-backend"

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildArgs = { GO_ROOT = "/app" }

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
restartPolicyInterval = "30s"
numReplicas = 1

# Resource allocation
[deploy.resources]
cpu = 512
memoryMB = 1024

# Environment variables
[env]
PORT = "8080"
ENVIRONMENT = "production"
LOG_LEVEL = "info"
CONFIG_PATH = "/app/configs"
CONFIG_FILE = "config.yaml"
DB_PATH = "/app/data/minimal.db"
DATABASE_ENABLED = "true"
AUTH_ENABLED = "false"

# TursoDB Configuration
TURSO_ENABLED = "true"
TURSO_URL = "libsql://urven-ryanlisse.aws-eu-west-1.turso.io"
TURSO_AUTH_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NDQwNDEwNzUsImlkIjoiMDdhOWRkMWMtNmViOS00YWU4LWFjNGUtNzJjOTJmNjMyOTA3IiwicmlkIjoiOWNkNjEwM2YtNTcxYi00ZTdiLWJmYjctNDVlODZhNjc4MDA5In0.ljq3muDkOYzSdhTtvu_Il5W61CAofy4r21ut9UVCmXkfUMs_gSQOEJAzZu3CmyMlowSrlPgorqFM21pQG-0mCQ"
TURSO_SYNC_ENABLED = "true"
TURSO_SYNC_INTERVAL_SECONDS = "300"

# MEXC Configuration
MEXC_BASE_URL = "https://api.mexc.com/api/v3"
MEXC_WEBSOCKET_URL = "wss://wbs.mexc.com/ws"
