// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/RyanLisse/go-crypto-bot-clean/clean_backend/internal/domain/model"
)

// ClerkGateway is an autogenerated mock type for the ClerkGateway type
type ClerkGateway struct {
	mock.Mock
}

type ClerkGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *ClerkGateway) EXPECT() *ClerkGateway_Expecter {
	return &ClerkGateway_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function with given fields: ctx, clerkUserID
func (_m *ClerkGateway) GetUser(ctx context.Context, clerkUserID string) (*model.User, error) {
	ret := _m.Called(ctx, clerkUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, clerkUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, clerkUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clerkUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClerkGateway_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type ClerkGateway_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - clerkUserID string
func (_e *ClerkGateway_Expecter) GetUser(ctx interface{}, clerkUserID interface{}) *ClerkGateway_GetUser_Call {
	return &ClerkGateway_GetUser_Call{Call: _e.mock.On("GetUser", ctx, clerkUserID)}
}

func (_c *ClerkGateway_GetUser_Call) Run(run func(ctx context.Context, clerkUserID string)) *ClerkGateway_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClerkGateway_GetUser_Call) Return(_a0 *model.User, _a1 error) *ClerkGateway_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClerkGateway_GetUser_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *ClerkGateway_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// VerifySession provides a mock function with given fields: ctx, sessionToken
func (_m *ClerkGateway) VerifySession(ctx context.Context, sessionToken string) (*model.User, error) {
	ret := _m.Called(ctx, sessionToken)

	if len(ret) == 0 {
		panic("no return value specified for VerifySession")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, sessionToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, sessionToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClerkGateway_VerifySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifySession'
type ClerkGateway_VerifySession_Call struct {
	*mock.Call
}

// VerifySession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionToken string
func (_e *ClerkGateway_Expecter) VerifySession(ctx interface{}, sessionToken interface{}) *ClerkGateway_VerifySession_Call {
	return &ClerkGateway_VerifySession_Call{Call: _e.mock.On("VerifySession", ctx, sessionToken)}
}

func (_c *ClerkGateway_VerifySession_Call) Run(run func(ctx context.Context, sessionToken string)) *ClerkGateway_VerifySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClerkGateway_VerifySession_Call) Return(_a0 *model.User, _a1 error) *ClerkGateway_VerifySession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClerkGateway_VerifySession_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *ClerkGateway_VerifySession_Call {
	_c.Call.Return(run)
	return _c
}

// NewClerkGateway creates a new instance of ClerkGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClerkGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClerkGateway {
	mock := &ClerkGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
