// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"

	model "github.com/RyanLisse/go-crypto-bot-clean/clean_backend/internal/domain/model"
)

// MEXCGateway is an autogenerated mock type for the MEXCGateway type
type MEXCGateway struct {
	mock.Mock
}

type MEXCGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MEXCGateway) EXPECT() *MEXCGateway_Expecter {
	return &MEXCGateway_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, symbol, orderID
func (_m *MEXCGateway) CancelOrder(ctx context.Context, symbol string, orderID string) error {
	ret := _m.Called(ctx, symbol, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, symbol, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MEXCGateway_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type MEXCGateway_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - orderID string
func (_e *MEXCGateway_Expecter) CancelOrder(ctx interface{}, symbol interface{}, orderID interface{}) *MEXCGateway_CancelOrder_Call {
	return &MEXCGateway_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, symbol, orderID)}
}

func (_c *MEXCGateway_CancelOrder_Call) Run(run func(ctx context.Context, symbol string, orderID string)) *MEXCGateway_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MEXCGateway_CancelOrder_Call) Return(_a0 error) *MEXCGateway_CancelOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MEXCGateway_CancelOrder_Call) RunAndReturn(run func(context.Context, string, string) error) *MEXCGateway_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountInfo provides a mock function with given fields: ctx
func (_m *MEXCGateway) GetAccountInfo(ctx context.Context) (model.AccountInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountInfo")
	}

	var r0 model.AccountInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (model.AccountInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) model.AccountInfo); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(model.AccountInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MEXCGateway_GetAccountInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountInfo'
type MEXCGateway_GetAccountInfo_Call struct {
	*mock.Call
}

// GetAccountInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MEXCGateway_Expecter) GetAccountInfo(ctx interface{}) *MEXCGateway_GetAccountInfo_Call {
	return &MEXCGateway_GetAccountInfo_Call{Call: _e.mock.On("GetAccountInfo", ctx)}
}

func (_c *MEXCGateway_GetAccountInfo_Call) Run(run func(ctx context.Context)) *MEXCGateway_GetAccountInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MEXCGateway_GetAccountInfo_Call) Return(_a0 model.AccountInfo, _a1 error) *MEXCGateway_GetAccountInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MEXCGateway_GetAccountInfo_Call) RunAndReturn(run func(context.Context) (model.AccountInfo, error)) *MEXCGateway_GetAccountInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetAssetBalance provides a mock function with given fields: ctx, asset
func (_m *MEXCGateway) GetAssetBalance(ctx context.Context, asset string) (decimal.Decimal, error) {
	ret := _m.Called(ctx, asset)

	if len(ret) == 0 {
		panic("no return value specified for GetAssetBalance")
	}

	var r0 decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (decimal.Decimal, error)); ok {
		return rf(ctx, asset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) decimal.Decimal); ok {
		r0 = rf(ctx, asset)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, asset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MEXCGateway_GetAssetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssetBalance'
type MEXCGateway_GetAssetBalance_Call struct {
	*mock.Call
}

// GetAssetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - asset string
func (_e *MEXCGateway_Expecter) GetAssetBalance(ctx interface{}, asset interface{}) *MEXCGateway_GetAssetBalance_Call {
	return &MEXCGateway_GetAssetBalance_Call{Call: _e.mock.On("GetAssetBalance", ctx, asset)}
}

func (_c *MEXCGateway_GetAssetBalance_Call) Run(run func(ctx context.Context, asset string)) *MEXCGateway_GetAssetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MEXCGateway_GetAssetBalance_Call) Return(_a0 decimal.Decimal, _a1 error) *MEXCGateway_GetAssetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MEXCGateway_GetAssetBalance_Call) RunAndReturn(run func(context.Context, string) (decimal.Decimal, error)) *MEXCGateway_GetAssetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetExchangeInfo provides a mock function with given fields: ctx
func (_m *MEXCGateway) GetExchangeInfo(ctx context.Context) (*model.ExchangeInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExchangeInfo")
	}

	var r0 *model.ExchangeInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*model.ExchangeInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *model.ExchangeInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ExchangeInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MEXCGateway_GetExchangeInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExchangeInfo'
type MEXCGateway_GetExchangeInfo_Call struct {
	*mock.Call
}

// GetExchangeInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MEXCGateway_Expecter) GetExchangeInfo(ctx interface{}) *MEXCGateway_GetExchangeInfo_Call {
	return &MEXCGateway_GetExchangeInfo_Call{Call: _e.mock.On("GetExchangeInfo", ctx)}
}

func (_c *MEXCGateway_GetExchangeInfo_Call) Run(run func(ctx context.Context)) *MEXCGateway_GetExchangeInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MEXCGateway_GetExchangeInfo_Call) Return(_a0 *model.ExchangeInfo, _a1 error) *MEXCGateway_GetExchangeInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MEXCGateway_GetExchangeInfo_Call) RunAndReturn(run func(context.Context) (*model.ExchangeInfo, error)) *MEXCGateway_GetExchangeInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderBook provides a mock function with given fields: ctx, symbol, depth
func (_m *MEXCGateway) GetOrderBook(ctx context.Context, symbol string, depth int) (model.OrderBook, error) {
	ret := _m.Called(ctx, symbol, depth)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderBook")
	}

	var r0 model.OrderBook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (model.OrderBook, error)); ok {
		return rf(ctx, symbol, depth)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) model.OrderBook); ok {
		r0 = rf(ctx, symbol, depth)
	} else {
		r0 = ret.Get(0).(model.OrderBook)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, symbol, depth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MEXCGateway_GetOrderBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderBook'
type MEXCGateway_GetOrderBook_Call struct {
	*mock.Call
}

// GetOrderBook is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - depth int
func (_e *MEXCGateway_Expecter) GetOrderBook(ctx interface{}, symbol interface{}, depth interface{}) *MEXCGateway_GetOrderBook_Call {
	return &MEXCGateway_GetOrderBook_Call{Call: _e.mock.On("GetOrderBook", ctx, symbol, depth)}
}

func (_c *MEXCGateway_GetOrderBook_Call) Run(run func(ctx context.Context, symbol string, depth int)) *MEXCGateway_GetOrderBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MEXCGateway_GetOrderBook_Call) Return(_a0 model.OrderBook, _a1 error) *MEXCGateway_GetOrderBook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MEXCGateway_GetOrderBook_Call) RunAndReturn(run func(context.Context, string, int) (model.OrderBook, error)) *MEXCGateway_GetOrderBook_Call {
	_c.Call.Return(run)
	return _c
}

// GetSymbols provides a mock function with given fields: ctx
func (_m *MEXCGateway) GetSymbols(ctx context.Context) ([]model.SymbolInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSymbols")
	}

	var r0 []model.SymbolInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.SymbolInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.SymbolInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SymbolInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MEXCGateway_GetSymbols_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSymbols'
type MEXCGateway_GetSymbols_Call struct {
	*mock.Call
}

// GetSymbols is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MEXCGateway_Expecter) GetSymbols(ctx interface{}) *MEXCGateway_GetSymbols_Call {
	return &MEXCGateway_GetSymbols_Call{Call: _e.mock.On("GetSymbols", ctx)}
}

func (_c *MEXCGateway_GetSymbols_Call) Run(run func(ctx context.Context)) *MEXCGateway_GetSymbols_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MEXCGateway_GetSymbols_Call) Return(_a0 []model.SymbolInfo, _a1 error) *MEXCGateway_GetSymbols_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MEXCGateway_GetSymbols_Call) RunAndReturn(run func(context.Context) ([]model.SymbolInfo, error)) *MEXCGateway_GetSymbols_Call {
	_c.Call.Return(run)
	return _c
}

// GetTicker provides a mock function with given fields: ctx, symbol
func (_m *MEXCGateway) GetTicker(ctx context.Context, symbol string) (model.Ticker, error) {
	ret := _m.Called(ctx, symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetTicker")
	}

	var r0 model.Ticker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Ticker, error)); ok {
		return rf(ctx, symbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Ticker); ok {
		r0 = rf(ctx, symbol)
	} else {
		r0 = ret.Get(0).(model.Ticker)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MEXCGateway_GetTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTicker'
type MEXCGateway_GetTicker_Call struct {
	*mock.Call
}

// GetTicker is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
func (_e *MEXCGateway_Expecter) GetTicker(ctx interface{}, symbol interface{}) *MEXCGateway_GetTicker_Call {
	return &MEXCGateway_GetTicker_Call{Call: _e.mock.On("GetTicker", ctx, symbol)}
}

func (_c *MEXCGateway_GetTicker_Call) Run(run func(ctx context.Context, symbol string)) *MEXCGateway_GetTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MEXCGateway_GetTicker_Call) Return(_a0 model.Ticker, _a1 error) *MEXCGateway_GetTicker_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MEXCGateway_GetTicker_Call) RunAndReturn(run func(context.Context, string) (model.Ticker, error)) *MEXCGateway_GetTicker_Call {
	_c.Call.Return(run)
	return _c
}

// PlaceOrder provides a mock function with given fields: ctx, order
func (_m *MEXCGateway) PlaceOrder(ctx context.Context, order model.OrderRequest) (model.PlaceOrderResponse, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for PlaceOrder")
	}

	var r0 model.PlaceOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderRequest) (model.PlaceOrderResponse, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderRequest) model.PlaceOrderResponse); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Get(0).(model.PlaceOrderResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.OrderRequest) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MEXCGateway_PlaceOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaceOrder'
type MEXCGateway_PlaceOrder_Call struct {
	*mock.Call
}

// PlaceOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.OrderRequest
func (_e *MEXCGateway_Expecter) PlaceOrder(ctx interface{}, order interface{}) *MEXCGateway_PlaceOrder_Call {
	return &MEXCGateway_PlaceOrder_Call{Call: _e.mock.On("PlaceOrder", ctx, order)}
}

func (_c *MEXCGateway_PlaceOrder_Call) Run(run func(ctx context.Context, order model.OrderRequest)) *MEXCGateway_PlaceOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderRequest))
	})
	return _c
}

func (_c *MEXCGateway_PlaceOrder_Call) Return(_a0 model.PlaceOrderResponse, _a1 error) *MEXCGateway_PlaceOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MEXCGateway_PlaceOrder_Call) RunAndReturn(run func(context.Context, model.OrderRequest) (model.PlaceOrderResponse, error)) *MEXCGateway_PlaceOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeToOrderBook provides a mock function with given fields: ctx, symbol, depth, handler
func (_m *MEXCGateway) SubscribeToOrderBook(ctx context.Context, symbol string, depth int, handler func(model.OrderBook)) error {
	ret := _m.Called(ctx, symbol, depth, handler)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeToOrderBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, func(model.OrderBook)) error); ok {
		r0 = rf(ctx, symbol, depth, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MEXCGateway_SubscribeToOrderBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeToOrderBook'
type MEXCGateway_SubscribeToOrderBook_Call struct {
	*mock.Call
}

// SubscribeToOrderBook is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - depth int
//   - handler func(model.OrderBook)
func (_e *MEXCGateway_Expecter) SubscribeToOrderBook(ctx interface{}, symbol interface{}, depth interface{}, handler interface{}) *MEXCGateway_SubscribeToOrderBook_Call {
	return &MEXCGateway_SubscribeToOrderBook_Call{Call: _e.mock.On("SubscribeToOrderBook", ctx, symbol, depth, handler)}
}

func (_c *MEXCGateway_SubscribeToOrderBook_Call) Run(run func(ctx context.Context, symbol string, depth int, handler func(model.OrderBook))) *MEXCGateway_SubscribeToOrderBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(func(model.OrderBook)))
	})
	return _c
}

func (_c *MEXCGateway_SubscribeToOrderBook_Call) Return(_a0 error) *MEXCGateway_SubscribeToOrderBook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MEXCGateway_SubscribeToOrderBook_Call) RunAndReturn(run func(context.Context, string, int, func(model.OrderBook)) error) *MEXCGateway_SubscribeToOrderBook_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeToTicker provides a mock function with given fields: ctx, symbol, handler
func (_m *MEXCGateway) SubscribeToTicker(ctx context.Context, symbol string, handler func(model.Ticker)) error {
	ret := _m.Called(ctx, symbol, handler)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeToTicker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, func(model.Ticker)) error); ok {
		r0 = rf(ctx, symbol, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MEXCGateway_SubscribeToTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeToTicker'
type MEXCGateway_SubscribeToTicker_Call struct {
	*mock.Call
}

// SubscribeToTicker is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - handler func(model.Ticker)
func (_e *MEXCGateway_Expecter) SubscribeToTicker(ctx interface{}, symbol interface{}, handler interface{}) *MEXCGateway_SubscribeToTicker_Call {
	return &MEXCGateway_SubscribeToTicker_Call{Call: _e.mock.On("SubscribeToTicker", ctx, symbol, handler)}
}

func (_c *MEXCGateway_SubscribeToTicker_Call) Run(run func(ctx context.Context, symbol string, handler func(model.Ticker))) *MEXCGateway_SubscribeToTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(func(model.Ticker)))
	})
	return _c
}

func (_c *MEXCGateway_SubscribeToTicker_Call) Return(_a0 error) *MEXCGateway_SubscribeToTicker_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MEXCGateway_SubscribeToTicker_Call) RunAndReturn(run func(context.Context, string, func(model.Ticker)) error) *MEXCGateway_SubscribeToTicker_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function with given fields: ctx, channel, symbol
func (_m *MEXCGateway) Unsubscribe(ctx context.Context, channel string, symbol string) error {
	ret := _m.Called(ctx, channel, symbol)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, channel, symbol)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MEXCGateway_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MEXCGateway_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - channel string
//   - symbol string
func (_e *MEXCGateway_Expecter) Unsubscribe(ctx interface{}, channel interface{}, symbol interface{}) *MEXCGateway_Unsubscribe_Call {
	return &MEXCGateway_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", ctx, channel, symbol)}
}

func (_c *MEXCGateway_Unsubscribe_Call) Run(run func(ctx context.Context, channel string, symbol string)) *MEXCGateway_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MEXCGateway_Unsubscribe_Call) Return(_a0 error) *MEXCGateway_Unsubscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MEXCGateway_Unsubscribe_Call) RunAndReturn(run func(context.Context, string, string) error) *MEXCGateway_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMEXCGateway creates a new instance of MEXCGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMEXCGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MEXCGateway {
	mock := &MEXCGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
