// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Notifier is an autogenerated mock type for the Notifier type
type Notifier struct {
	mock.Mock
}

type Notifier_Expecter struct {
	mock *mock.Mock
}

func (_m *Notifier) EXPECT() *Notifier_Expecter {
	return &Notifier_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, recipient, subject, message
func (_m *Notifier) Send(ctx context.Context, recipient string, subject string, message string) error {
	ret := _m.Called(ctx, recipient, subject, message)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, recipient, subject, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Notifier_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Notifier_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - recipient string
//   - subject string
//   - message string
func (_e *Notifier_Expecter) Send(ctx interface{}, recipient interface{}, subject interface{}, message interface{}) *Notifier_Send_Call {
	return &Notifier_Send_Call{Call: _e.mock.On("Send", ctx, recipient, subject, message)}
}

func (_c *Notifier_Send_Call) Run(run func(ctx context.Context, recipient string, subject string, message string)) *Notifier_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Notifier_Send_Call) Return(_a0 error) *Notifier_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Notifier_Send_Call) RunAndReturn(run func(context.Context, string, string, string) error) *Notifier_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendUrgent provides a mock function with given fields: ctx, recipient, subject, message
func (_m *Notifier) SendUrgent(ctx context.Context, recipient string, subject string, message string) error {
	ret := _m.Called(ctx, recipient, subject, message)

	if len(ret) == 0 {
		panic("no return value specified for SendUrgent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, recipient, subject, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Notifier_SendUrgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUrgent'
type Notifier_SendUrgent_Call struct {
	*mock.Call
}

// SendUrgent is a helper method to define mock.On call
//   - ctx context.Context
//   - recipient string
//   - subject string
//   - message string
func (_e *Notifier_Expecter) SendUrgent(ctx interface{}, recipient interface{}, subject interface{}, message interface{}) *Notifier_SendUrgent_Call {
	return &Notifier_SendUrgent_Call{Call: _e.mock.On("SendUrgent", ctx, recipient, subject, message)}
}

func (_c *Notifier_SendUrgent_Call) Run(run func(ctx context.Context, recipient string, subject string, message string)) *Notifier_SendUrgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Notifier_SendUrgent_Call) Return(_a0 error) *Notifier_SendUrgent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Notifier_SendUrgent_Call) RunAndReturn(run func(context.Context, string, string, string) error) *Notifier_SendUrgent_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotifier creates a new instance of Notifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Notifier {
	mock := &Notifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
