// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	market "github.com/RyanLisse/go-crypto-bot-clean/backend/internal/domain/model/market"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MarketCache is an autogenerated mock type for the MarketCache type
type MarketCache struct {
	mock.Mock
}

// CacheCandle provides a mock function with given fields: candle
func (_m *MarketCache) CacheCandle(candle *market.Candle) {
	_m.Called(candle)
}

// CacheOrderBook provides a mock function with given fields: orderbook
func (_m *MarketCache) CacheOrderBook(orderbook *market.OrderBook) {
	_m.Called(orderbook)
}

// CacheTicker provides a mock function with given fields: ticker
func (_m *MarketCache) CacheTicker(ticker *market.Ticker) {
	_m.Called(ticker)
}

// Clear provides a mock function with no fields
func (_m *MarketCache) Clear() {
	_m.Called()
}

// GetAllTickers provides a mock function with given fields: ctx, exchange
func (_m *MarketCache) GetAllTickers(ctx context.Context, exchange string) ([]*market.Ticker, bool) {
	ret := _m.Called(ctx, exchange)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTickers")
	}

	var r0 []*market.Ticker
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*market.Ticker, bool)); ok {
		return rf(ctx, exchange)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*market.Ticker); ok {
		r0 = rf(ctx, exchange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*market.Ticker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, exchange)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetCandle provides a mock function with given fields: ctx, exchange, symbol, interval, openTime
func (_m *MarketCache) GetCandle(ctx context.Context, exchange string, symbol string, interval market.Interval, openTime time.Time) (*market.Candle, bool) {
	ret := _m.Called(ctx, exchange, symbol, interval, openTime)

	if len(ret) == 0 {
		panic("no return value specified for GetCandle")
	}

	var r0 *market.Candle
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, string, market.Interval, time.Time) (*market.Candle, bool)); ok {
		return rf(ctx, exchange, symbol, interval, openTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, market.Interval, time.Time) *market.Candle); ok {
		r0 = rf(ctx, exchange, symbol, interval, openTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*market.Candle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, market.Interval, time.Time) bool); ok {
		r1 = rf(ctx, exchange, symbol, interval, openTime)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetLatestCandle provides a mock function with given fields: ctx, exchange, symbol, interval
func (_m *MarketCache) GetLatestCandle(ctx context.Context, exchange string, symbol string, interval market.Interval) (*market.Candle, bool) {
	ret := _m.Called(ctx, exchange, symbol, interval)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestCandle")
	}

	var r0 *market.Candle
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, string, market.Interval) (*market.Candle, bool)); ok {
		return rf(ctx, exchange, symbol, interval)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, market.Interval) *market.Candle); ok {
		r0 = rf(ctx, exchange, symbol, interval)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*market.Candle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, market.Interval) bool); ok {
		r1 = rf(ctx, exchange, symbol, interval)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetLatestTickers provides a mock function with given fields: ctx
func (_m *MarketCache) GetLatestTickers(ctx context.Context) ([]*market.Ticker, bool) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestTickers")
	}

	var r0 []*market.Ticker
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context) ([]*market.Ticker, bool)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*market.Ticker); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*market.Ticker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetOrderBook provides a mock function with given fields: ctx, exchange, symbol
func (_m *MarketCache) GetOrderBook(ctx context.Context, exchange string, symbol string) (*market.OrderBook, bool) {
	ret := _m.Called(ctx, exchange, symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderBook")
	}

	var r0 *market.OrderBook
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*market.OrderBook, bool)); ok {
		return rf(ctx, exchange, symbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *market.OrderBook); ok {
		r0 = rf(ctx, exchange, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*market.OrderBook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = rf(ctx, exchange, symbol)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetTicker provides a mock function with given fields: ctx, exchange, symbol
func (_m *MarketCache) GetTicker(ctx context.Context, exchange string, symbol string) (*market.Ticker, bool) {
	ret := _m.Called(ctx, exchange, symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetTicker")
	}

	var r0 *market.Ticker
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*market.Ticker, bool)); ok {
		return rf(ctx, exchange, symbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *market.Ticker); ok {
		r0 = rf(ctx, exchange, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*market.Ticker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = rf(ctx, exchange, symbol)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// SetCandleExpiry provides a mock function with given fields: d
func (_m *MarketCache) SetCandleExpiry(d time.Duration) {
	_m.Called(d)
}

// SetOrderbookExpiry provides a mock function with given fields: d
func (_m *MarketCache) SetOrderbookExpiry(d time.Duration) {
	_m.Called(d)
}

// SetTickerExpiry provides a mock function with given fields: d
func (_m *MarketCache) SetTickerExpiry(d time.Duration) {
	_m.Called(d)
}

// StartCleanupTask provides a mock function with given fields: ctx, interval
func (_m *MarketCache) StartCleanupTask(ctx context.Context, interval time.Duration) {
	_m.Called(ctx, interval)
}

// NewMarketCache creates a new instance of MarketCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketCache {
	mock := &MarketCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
