// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/RyanLisse/go-crypto-bot-clean/backend/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// PositionRepository is an autogenerated mock type for the PositionRepository type
type PositionRepository struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx, filters
func (_m *PositionRepository) Count(ctx context.Context, filters map[string]interface{}) (int64, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) (int64, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) int64); ok {
		r0 = rf(ctx, filters)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, position
func (_m *PositionRepository) Create(ctx context.Context, position *model.Position) error {
	ret := _m.Called(ctx, position)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Position) error); ok {
		r0 = rf(ctx, position)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PositionRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveByUser provides a mock function with given fields: ctx, userID
func (_m *PositionRepository) GetActiveByUser(ctx context.Context, userID string) ([]*model.Position, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByUser")
	}

	var r0 []*model.Position
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.Position, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.Position); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Position)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PositionRepository) GetByID(ctx context.Context, id string) (*model.Position, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Position
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Position, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Position); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Position)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBySymbol provides a mock function with given fields: ctx, symbol, page, limit
func (_m *PositionRepository) GetBySymbol(ctx context.Context, symbol string, page int, limit int) ([]*model.Position, error) {
	ret := _m.Called(ctx, symbol, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetBySymbol")
	}

	var r0 []*model.Position
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*model.Position, error)); ok {
		return rf(ctx, symbol, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*model.Position); ok {
		r0 = rf(ctx, symbol, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Position)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, symbol, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBySymbolAndUser provides a mock function with given fields: ctx, symbol, userID, page, limit
func (_m *PositionRepository) GetBySymbolAndUser(ctx context.Context, symbol string, userID string, page int, limit int) ([]*model.Position, error) {
	ret := _m.Called(ctx, symbol, userID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetBySymbolAndUser")
	}

	var r0 []*model.Position
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) ([]*model.Position, error)); ok {
		return rf(ctx, symbol, userID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) []*model.Position); ok {
		r0 = rf(ctx, symbol, userID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Position)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = rf(ctx, symbol, userID, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserID provides a mock function with given fields: ctx, userID, page, limit
func (_m *PositionRepository) GetByUserID(ctx context.Context, userID string, page int, limit int) ([]*model.Position, error) {
	ret := _m.Called(ctx, userID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*model.Position
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*model.Position, error)); ok {
		return rf(ctx, userID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*model.Position); ok {
		r0 = rf(ctx, userID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Position)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOpenPositionsByUserID provides a mock function with given fields: ctx, userID
func (_m *PositionRepository) GetOpenPositionsByUserID(ctx context.Context, userID string) ([]*model.Position, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOpenPositionsByUserID")
	}

	var r0 []*model.Position
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.Position, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.Position); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Position)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, position
func (_m *PositionRepository) Update(ctx context.Context, position *model.Position) error {
	ret := _m.Called(ctx, position)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Position) error); ok {
		r0 = rf(ctx, position)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPositionRepository creates a new instance of PositionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPositionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PositionRepository {
	mock := &PositionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
