package advanced

import (
	"time"
)

// SignalType represents the type of trading signal
type SignalType string

const (
	SignalBuy   SignalType = "BUY"
	SignalSell  SignalType = "SELL"
	SignalHold  SignalType = "HOLD"
	SignalClose SignalType = "CLOSE"
)

// Signal represents a trading signal generated by a strategy
type Signal struct {
	Symbol           string                 // The trading pair symbol
	Type             SignalType             // Buy, sell, or hold
	Confidence       float64                // Signal confidence score (0-1.0)
	Price            float64                // Current price when signal was generated
	TargetPrice      float64                // Target price if applicable
	StopLoss         float64                // Recommended stop-loss level
	TakeProfit       float64                // Recommended take-profit level
	Timeframe        string                 // Timeframe this signal is based on (e.g., "15m", "1h")
	Timestamp        time.Time              // When this signal was generated
	ExpirationTime   time.Time              // When this signal should be considered invalid
	Metadata         map[string]interface{} // Additional strategy-specific information
	RecommendedSize  float64                // Recommended position size (0-1.0)
}
