package mocks

package mocks

import (
	usecase "github.com/RyanLisse/go-crypto-bot-clean/backend/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// TradeUsecase is an autogenerated mock type for the TradeUsecase type
type TradeUsecase struct {
	mock.Mock
}

// ExecuteMarketBuy provides a mock function with given fields: order
func (_m *TradeUsecase) ExecuteMarketBuy(order usecase.OrderParameters) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteMarketBuy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(usecase.OrderParameters) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTradeUsecase creates a new instance of TradeUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTradeUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TradeUsecase {
	mock := &TradeUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
