// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/RyanLisse/go-crypto-bot-clean/clean_backend/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// WalletService is an autogenerated mock type for the WalletService type
type WalletService struct {
	mock.Mock
}

type WalletService_Expecter struct {
	mock *mock.Mock
}

func (_m *WalletService) EXPECT() *WalletService_Expecter {
	return &WalletService_Expecter{mock: &_m.Mock}
}

// CheckVerificationStatus provides a mock function with given fields: ctx, walletID
func (_m *WalletService) CheckVerificationStatus(ctx context.Context, walletID uuid.UUID) (model.VerificationStatus, error) {
	ret := _m.Called(ctx, walletID)

	if len(ret) == 0 {
		panic("no return value specified for CheckVerificationStatus")
	}

	var r0 model.VerificationStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.VerificationStatus, error)); ok {
		return rf(ctx, walletID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.VerificationStatus); ok {
		r0 = rf(ctx, walletID)
	} else {
		r0 = ret.Get(0).(model.VerificationStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, walletID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WalletService_CheckVerificationStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckVerificationStatus'
type WalletService_CheckVerificationStatus_Call struct {
	*mock.Call
}

// CheckVerificationStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - walletID uuid.UUID
func (_e *WalletService_Expecter) CheckVerificationStatus(ctx interface{}, walletID interface{}) *WalletService_CheckVerificationStatus_Call {
	return &WalletService_CheckVerificationStatus_Call{Call: _e.mock.On("CheckVerificationStatus", ctx, walletID)}
}

func (_c *WalletService_CheckVerificationStatus_Call) Run(run func(ctx context.Context, walletID uuid.UUID)) *WalletService_CheckVerificationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *WalletService_CheckVerificationStatus_Call) Return(_a0 model.VerificationStatus, _a1 error) *WalletService_CheckVerificationStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WalletService_CheckVerificationStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.VerificationStatus, error)) *WalletService_CheckVerificationStatus_Call {
	_c.Call.Return(run)
	return _c
}

// CreateExchangeWallet provides a mock function with given fields: ctx, userID, exchangeID, exchangeName, isPrimary
func (_m *WalletService) CreateExchangeWallet(ctx context.Context, userID uuid.UUID, exchangeID string, exchangeName string, isPrimary bool) (*model.Wallet, error) {
	ret := _m.Called(ctx, userID, exchangeID, exchangeName, isPrimary)

	if len(ret) == 0 {
		panic("no return value specified for CreateExchangeWallet")
	}

	var r0 *model.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, bool) (*model.Wallet, error)); ok {
		return rf(ctx, userID, exchangeID, exchangeName, isPrimary)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, bool) *model.Wallet); ok {
		r0 = rf(ctx, userID, exchangeID, exchangeName, isPrimary)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, bool) error); ok {
		r1 = rf(ctx, userID, exchangeID, exchangeName, isPrimary)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WalletService_CreateExchangeWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExchangeWallet'
type WalletService_CreateExchangeWallet_Call struct {
	*mock.Call
}

// CreateExchangeWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - exchangeID string
//   - exchangeName string
//   - isPrimary bool
func (_e *WalletService_Expecter) CreateExchangeWallet(ctx interface{}, userID interface{}, exchangeID interface{}, exchangeName interface{}, isPrimary interface{}) *WalletService_CreateExchangeWallet_Call {
	return &WalletService_CreateExchangeWallet_Call{Call: _e.mock.On("CreateExchangeWallet", ctx, userID, exchangeID, exchangeName, isPrimary)}
}

func (_c *WalletService_CreateExchangeWallet_Call) Run(run func(ctx context.Context, userID uuid.UUID, exchangeID string, exchangeName string, isPrimary bool)) *WalletService_CreateExchangeWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *WalletService_CreateExchangeWallet_Call) Return(_a0 *model.Wallet, _a1 error) *WalletService_CreateExchangeWallet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WalletService_CreateExchangeWallet_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, bool) (*model.Wallet, error)) *WalletService_CreateExchangeWallet_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWeb3Wallet provides a mock function with given fields: ctx, userID, address, network, isPrimary
func (_m *WalletService) CreateWeb3Wallet(ctx context.Context, userID uuid.UUID, address string, network string, isPrimary bool) (*model.Wallet, error) {
	ret := _m.Called(ctx, userID, address, network, isPrimary)

	if len(ret) == 0 {
		panic("no return value specified for CreateWeb3Wallet")
	}

	var r0 *model.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, bool) (*model.Wallet, error)); ok {
		return rf(ctx, userID, address, network, isPrimary)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, bool) *model.Wallet); ok {
		r0 = rf(ctx, userID, address, network, isPrimary)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, bool) error); ok {
		r1 = rf(ctx, userID, address, network, isPrimary)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WalletService_CreateWeb3Wallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWeb3Wallet'
type WalletService_CreateWeb3Wallet_Call struct {
	*mock.Call
}

// CreateWeb3Wallet is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - address string
//   - network string
//   - isPrimary bool
func (_e *WalletService_Expecter) CreateWeb3Wallet(ctx interface{}, userID interface{}, address interface{}, network interface{}, isPrimary interface{}) *WalletService_CreateWeb3Wallet_Call {
	return &WalletService_CreateWeb3Wallet_Call{Call: _e.mock.On("CreateWeb3Wallet", ctx, userID, address, network, isPrimary)}
}

func (_c *WalletService_CreateWeb3Wallet_Call) Run(run func(ctx context.Context, userID uuid.UUID, address string, network string, isPrimary bool)) *WalletService_CreateWeb3Wallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *WalletService_CreateWeb3Wallet_Call) Return(_a0 *model.Wallet, _a1 error) *WalletService_CreateWeb3Wallet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WalletService_CreateWeb3Wallet_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, bool) (*model.Wallet, error)) *WalletService_CreateWeb3Wallet_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWallet provides a mock function with given fields: ctx, walletID, userID
func (_m *WalletService) DeleteWallet(ctx context.Context, walletID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, walletID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWallet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, walletID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WalletService_DeleteWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWallet'
type WalletService_DeleteWallet_Call struct {
	*mock.Call
}

// DeleteWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - walletID uuid.UUID
//   - userID uuid.UUID
func (_e *WalletService_Expecter) DeleteWallet(ctx interface{}, walletID interface{}, userID interface{}) *WalletService_DeleteWallet_Call {
	return &WalletService_DeleteWallet_Call{Call: _e.mock.On("DeleteWallet", ctx, walletID, userID)}
}

func (_c *WalletService_DeleteWallet_Call) Run(run func(ctx context.Context, walletID uuid.UUID, userID uuid.UUID)) *WalletService_DeleteWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *WalletService_DeleteWallet_Call) Return(_a0 error) *WalletService_DeleteWallet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WalletService_DeleteWallet_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *WalletService_DeleteWallet_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrimaryWallet provides a mock function with given fields: ctx, userID
func (_m *WalletService) GetPrimaryWallet(ctx context.Context, userID uuid.UUID) (*model.Wallet, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPrimaryWallet")
	}

	var r0 *model.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Wallet, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Wallet); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WalletService_GetPrimaryWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrimaryWallet'
type WalletService_GetPrimaryWallet_Call struct {
	*mock.Call
}

// GetPrimaryWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *WalletService_Expecter) GetPrimaryWallet(ctx interface{}, userID interface{}) *WalletService_GetPrimaryWallet_Call {
	return &WalletService_GetPrimaryWallet_Call{Call: _e.mock.On("GetPrimaryWallet", ctx, userID)}
}

func (_c *WalletService_GetPrimaryWallet_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *WalletService_GetPrimaryWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *WalletService_GetPrimaryWallet_Call) Return(_a0 *model.Wallet, _a1 error) *WalletService_GetPrimaryWallet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WalletService_GetPrimaryWallet_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Wallet, error)) *WalletService_GetPrimaryWallet_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserWallets provides a mock function with given fields: ctx, userID
func (_m *WalletService) GetUserWallets(ctx context.Context, userID uuid.UUID) ([]*model.Wallet, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWallets")
	}

	var r0 []*model.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Wallet, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Wallet); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WalletService_GetUserWallets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserWallets'
type WalletService_GetUserWallets_Call struct {
	*mock.Call
}

// GetUserWallets is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *WalletService_Expecter) GetUserWallets(ctx interface{}, userID interface{}) *WalletService_GetUserWallets_Call {
	return &WalletService_GetUserWallets_Call{Call: _e.mock.On("GetUserWallets", ctx, userID)}
}

func (_c *WalletService_GetUserWallets_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *WalletService_GetUserWallets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *WalletService_GetUserWallets_Call) Return(_a0 []*model.Wallet, _a1 error) *WalletService_GetUserWallets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WalletService_GetUserWallets_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Wallet, error)) *WalletService_GetUserWallets_Call {
	_c.Call.Return(run)
	return _c
}

// GetWallet provides a mock function with given fields: ctx, id
func (_m *WalletService) GetWallet(ctx context.Context, id uuid.UUID) (*model.Wallet, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWallet")
	}

	var r0 *model.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Wallet, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Wallet); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WalletService_GetWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWallet'
type WalletService_GetWallet_Call struct {
	*mock.Call
}

// GetWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *WalletService_Expecter) GetWallet(ctx interface{}, id interface{}) *WalletService_GetWallet_Call {
	return &WalletService_GetWallet_Call{Call: _e.mock.On("GetWallet", ctx, id)}
}

func (_c *WalletService_GetWallet_Call) Run(run func(ctx context.Context, id uuid.UUID)) *WalletService_GetWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *WalletService_GetWallet_Call) Return(_a0 *model.Wallet, _a1 error) *WalletService_GetWallet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WalletService_GetWallet_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Wallet, error)) *WalletService_GetWallet_Call {
	_c.Call.Return(run)
	return _c
}

// SetPrimaryWallet provides a mock function with given fields: ctx, walletID, userID
func (_m *WalletService) SetPrimaryWallet(ctx context.Context, walletID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, walletID, userID)

	if len(ret) == 0 {
		panic("no return value specified for SetPrimaryWallet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, walletID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WalletService_SetPrimaryWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPrimaryWallet'
type WalletService_SetPrimaryWallet_Call struct {
	*mock.Call
}

// SetPrimaryWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - walletID uuid.UUID
//   - userID uuid.UUID
func (_e *WalletService_Expecter) SetPrimaryWallet(ctx interface{}, walletID interface{}, userID interface{}) *WalletService_SetPrimaryWallet_Call {
	return &WalletService_SetPrimaryWallet_Call{Call: _e.mock.On("SetPrimaryWallet", ctx, walletID, userID)}
}

func (_c *WalletService_SetPrimaryWallet_Call) Run(run func(ctx context.Context, walletID uuid.UUID, userID uuid.UUID)) *WalletService_SetPrimaryWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *WalletService_SetPrimaryWallet_Call) Return(_a0 error) *WalletService_SetPrimaryWallet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WalletService_SetPrimaryWallet_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *WalletService_SetPrimaryWallet_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBalances provides a mock function with given fields: ctx, walletID, balances
func (_m *WalletService) UpdateBalances(ctx context.Context, walletID uuid.UUID, balances []*model.Balance) error {
	ret := _m.Called(ctx, walletID, balances)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBalances")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []*model.Balance) error); ok {
		r0 = rf(ctx, walletID, balances)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WalletService_UpdateBalances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBalances'
type WalletService_UpdateBalances_Call struct {
	*mock.Call
}

// UpdateBalances is a helper method to define mock.On call
//   - ctx context.Context
//   - walletID uuid.UUID
//   - balances []*model.Balance
func (_e *WalletService_Expecter) UpdateBalances(ctx interface{}, walletID interface{}, balances interface{}) *WalletService_UpdateBalances_Call {
	return &WalletService_UpdateBalances_Call{Call: _e.mock.On("UpdateBalances", ctx, walletID, balances)}
}

func (_c *WalletService_UpdateBalances_Call) Run(run func(ctx context.Context, walletID uuid.UUID, balances []*model.Balance)) *WalletService_UpdateBalances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]*model.Balance))
	})
	return _c
}

func (_c *WalletService_UpdateBalances_Call) Return(_a0 error) *WalletService_UpdateBalances_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WalletService_UpdateBalances_Call) RunAndReturn(run func(context.Context, uuid.UUID, []*model.Balance) error) *WalletService_UpdateBalances_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyWallet provides a mock function with given fields: ctx, walletID
func (_m *WalletService) VerifyWallet(ctx context.Context, walletID uuid.UUID) error {
	ret := _m.Called(ctx, walletID)

	if len(ret) == 0 {
		panic("no return value specified for VerifyWallet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, walletID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WalletService_VerifyWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyWallet'
type WalletService_VerifyWallet_Call struct {
	*mock.Call
}

// VerifyWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - walletID uuid.UUID
func (_e *WalletService_Expecter) VerifyWallet(ctx interface{}, walletID interface{}) *WalletService_VerifyWallet_Call {
	return &WalletService_VerifyWallet_Call{Call: _e.mock.On("VerifyWallet", ctx, walletID)}
}

func (_c *WalletService_VerifyWallet_Call) Run(run func(ctx context.Context, walletID uuid.UUID)) *WalletService_VerifyWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *WalletService_VerifyWallet_Call) Return(_a0 error) *WalletService_VerifyWallet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WalletService_VerifyWallet_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *WalletService_VerifyWallet_Call {
	_c.Call.Return(run)
	return _c
}

// NewWalletService creates a new instance of WalletService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletService {
	mock := &WalletService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
