package types

import (
	"context"
	"time"

	"go-crypto-bot-clean/backend/internal/domain/models"
)

// SignalType represents the type of trading signal
type SignalType string

const (
	BUY   SignalType = "BUY"
	SELL  SignalType = "SELL"
	HOLD  SignalType = "HOLD"
	CLOSE SignalType = "CLOSE"
)

// Signal represents a trading signal generated by a strategy
type Signal struct {
	Symbol          string                 `json:"symbol"`
	Type            SignalType             `json:"type"`
	Confidence      float64                `json:"confidence"`
	Price           float64                `json:"price"`
	TargetPrice     float64                `json:"targetPrice,omitempty"`
	StopLoss        float64                `json:"stopLoss,omitempty"`
	TakeProfit      float64                `json:"takeProfit,omitempty"`
	Timeframe       string                 `json:"timeframe,omitempty"`
	Timestamp       time.Time              `json:"timestamp"`
	ExpirationTime  time.Time              `json:"expirationTime,omitempty"`
	Metadata        map[string]interface{} `json:"metadata,omitempty"`
	RecommendedSize float64                `json:"recommendedSize,omitempty"`
}

// Strategy defines the interface that all trading strategies must implement
type Strategy interface {
	// GetName returns the name of the strategy
	GetName() string

	// Initialize prepares the strategy with initial configuration
	Initialize(ctx context.Context, config map[string]interface{}) error

	// UpdateParameters updates the strategy parameters
	UpdateParameters(ctx context.Context, params map[string]interface{}) error

	// OnTickerUpdate processes a new ticker update and may generate a signal
	OnTickerUpdate(ctx context.Context, ticker *models.Ticker) (*Signal, error)

	// OnCandleUpdate processes a new candle and may generate a signal
	OnCandleUpdate(ctx context.Context, candle *models.Candle) (*Signal, error)

	// OnTradeUpdate processes a new trade and may generate a signal
	OnTradeUpdate(ctx context.Context, trade *models.Trade) (*Signal, error)

	// OnMarketDepthUpdate processes a new market depth update and may generate a signal
	OnMarketDepthUpdate(ctx context.Context, depth *models.OrderBook) (*Signal, error)

	// OnTimerEvent processes a scheduled timer event
	OnTimerEvent(ctx context.Context, eventType string) (*Signal, error)

	// GetTimeframes returns the timeframes this strategy requires
	GetTimeframes() []string

	// GetRequiredDataTypes returns the types of data this strategy needs
	GetRequiredDataTypes() []string

	// PerformBacktest runs a backtest of the strategy on historical data
	PerformBacktest(ctx context.Context, historicalData []*models.Candle, params map[string]interface{}) ([]*Signal, interface{}, error)
}
