package types

import (
	"time"
)

// Signal represents a trading signal generated by a strategy
type Signal struct {
	Symbol    string
	Side      string
	Quantity  float64
	Price     float64
	Timestamp time.Time
	Reason    string
}

// EquityPoint represents a point in the equity curve
type EquityPoint struct {
	Timestamp time.Time
	Equity    float64
}

// DrawdownPoint represents a point in the drawdown curve
type DrawdownPoint struct {
	Timestamp time.Time
	Drawdown  float64
}

// PerformanceMetrics contains performance metrics for a backtest
type PerformanceMetrics struct {
	TotalReturn         float64
	AnnualizedReturn    float64
	SharpeRatio         float64
	MaxDrawdown         float64
	MaxDrawdownPercent  float64
	WinRate             float64
	ProfitFactor        float64
	AverageWin          float64
	AverageLoss         float64
	TotalTrades         int
	ProfitableTrades    int
	UnprofitableTrades  int
	AverageTradePercent float64

	// Additional fields for compatibility
	WinningTrades      int
	LosingTrades       int
	BreakEvenTrades    int
	LargestProfitTrade float64
	LargestLossTrade   float64
	AverageProfitTrade float64
	AverageLossTrade   float64
	ExpectedPayoff     float64
	AverageHoldingTime time.Duration
	SortinoRatio       float64
	CalmarRatio        float64
	OmegaRatio         float64
	InformationRatio   float64
}
