// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/RyanLisse/go-crypto-bot-clean/clean_backend/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// AutoBuyRuleRepository is an autogenerated mock type for the AutoBuyRuleRepository type
type AutoBuyRuleRepository struct {
	mock.Mock
}

type AutoBuyRuleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AutoBuyRuleRepository) EXPECT() *AutoBuyRuleRepository_Expecter {
	return &AutoBuyRuleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, rule
func (_m *AutoBuyRuleRepository) Create(ctx context.Context, rule *model.AutoBuyRule) error {
	ret := _m.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AutoBuyRule) error); ok {
		r0 = rf(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AutoBuyRuleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AutoBuyRuleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - rule *model.AutoBuyRule
func (_e *AutoBuyRuleRepository_Expecter) Create(ctx interface{}, rule interface{}) *AutoBuyRuleRepository_Create_Call {
	return &AutoBuyRuleRepository_Create_Call{Call: _e.mock.On("Create", ctx, rule)}
}

func (_c *AutoBuyRuleRepository_Create_Call) Run(run func(ctx context.Context, rule *model.AutoBuyRule)) *AutoBuyRuleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.AutoBuyRule))
	})
	return _c
}

func (_c *AutoBuyRuleRepository_Create_Call) Return(_a0 error) *AutoBuyRuleRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AutoBuyRuleRepository_Create_Call) RunAndReturn(run func(context.Context, *model.AutoBuyRule) error) *AutoBuyRuleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *AutoBuyRuleRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AutoBuyRuleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type AutoBuyRuleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *AutoBuyRuleRepository_Expecter) Delete(ctx interface{}, id interface{}) *AutoBuyRuleRepository_Delete_Call {
	return &AutoBuyRuleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *AutoBuyRuleRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *AutoBuyRuleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AutoBuyRuleRepository_Delete_Call) Return(_a0 error) *AutoBuyRuleRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AutoBuyRuleRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *AutoBuyRuleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetActive provides a mock function with given fields: ctx
func (_m *AutoBuyRuleRepository) GetActive(ctx context.Context) ([]*model.AutoBuyRule, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActive")
	}

	var r0 []*model.AutoBuyRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.AutoBuyRule, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.AutoBuyRule); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AutoBuyRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AutoBuyRuleRepository_GetActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActive'
type AutoBuyRuleRepository_GetActive_Call struct {
	*mock.Call
}

// GetActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AutoBuyRuleRepository_Expecter) GetActive(ctx interface{}) *AutoBuyRuleRepository_GetActive_Call {
	return &AutoBuyRuleRepository_GetActive_Call{Call: _e.mock.On("GetActive", ctx)}
}

func (_c *AutoBuyRuleRepository_GetActive_Call) Run(run func(ctx context.Context)) *AutoBuyRuleRepository_GetActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AutoBuyRuleRepository_GetActive_Call) Return(_a0 []*model.AutoBuyRule, _a1 error) *AutoBuyRuleRepository_GetActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AutoBuyRuleRepository_GetActive_Call) RunAndReturn(run func(context.Context) ([]*model.AutoBuyRule, error)) *AutoBuyRuleRepository_GetActive_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *AutoBuyRuleRepository) GetByID(ctx context.Context, id string) (*model.AutoBuyRule, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.AutoBuyRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.AutoBuyRule, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.AutoBuyRule); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AutoBuyRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AutoBuyRuleRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type AutoBuyRuleRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *AutoBuyRuleRepository_Expecter) GetByID(ctx interface{}, id interface{}) *AutoBuyRuleRepository_GetByID_Call {
	return &AutoBuyRuleRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *AutoBuyRuleRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *AutoBuyRuleRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AutoBuyRuleRepository_GetByID_Call) Return(_a0 *model.AutoBuyRule, _a1 error) *AutoBuyRuleRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AutoBuyRuleRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*model.AutoBuyRule, error)) *AutoBuyRuleRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySymbol provides a mock function with given fields: ctx, symbol
func (_m *AutoBuyRuleRepository) GetBySymbol(ctx context.Context, symbol string) ([]*model.AutoBuyRule, error) {
	ret := _m.Called(ctx, symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetBySymbol")
	}

	var r0 []*model.AutoBuyRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.AutoBuyRule, error)); ok {
		return rf(ctx, symbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.AutoBuyRule); ok {
		r0 = rf(ctx, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AutoBuyRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AutoBuyRuleRepository_GetBySymbol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySymbol'
type AutoBuyRuleRepository_GetBySymbol_Call struct {
	*mock.Call
}

// GetBySymbol is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
func (_e *AutoBuyRuleRepository_Expecter) GetBySymbol(ctx interface{}, symbol interface{}) *AutoBuyRuleRepository_GetBySymbol_Call {
	return &AutoBuyRuleRepository_GetBySymbol_Call{Call: _e.mock.On("GetBySymbol", ctx, symbol)}
}

func (_c *AutoBuyRuleRepository_GetBySymbol_Call) Run(run func(ctx context.Context, symbol string)) *AutoBuyRuleRepository_GetBySymbol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AutoBuyRuleRepository_GetBySymbol_Call) Return(_a0 []*model.AutoBuyRule, _a1 error) *AutoBuyRuleRepository_GetBySymbol_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AutoBuyRuleRepository_GetBySymbol_Call) RunAndReturn(run func(context.Context, string) ([]*model.AutoBuyRule, error)) *AutoBuyRuleRepository_GetBySymbol_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *AutoBuyRuleRepository) GetByUserID(ctx context.Context, userID string) ([]*model.AutoBuyRule, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*model.AutoBuyRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.AutoBuyRule, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.AutoBuyRule); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AutoBuyRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AutoBuyRuleRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type AutoBuyRuleRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *AutoBuyRuleRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *AutoBuyRuleRepository_GetByUserID_Call {
	return &AutoBuyRuleRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *AutoBuyRuleRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *AutoBuyRuleRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AutoBuyRuleRepository_GetByUserID_Call) Return(_a0 []*model.AutoBuyRule, _a1 error) *AutoBuyRuleRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AutoBuyRuleRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, string) ([]*model.AutoBuyRule, error)) *AutoBuyRuleRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function with given fields: ctx, limit, offset
func (_m *AutoBuyRuleRepository) ListAll(ctx context.Context, limit int, offset int) ([]*model.AutoBuyRule, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []*model.AutoBuyRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*model.AutoBuyRule, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*model.AutoBuyRule); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AutoBuyRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AutoBuyRuleRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type AutoBuyRuleRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *AutoBuyRuleRepository_Expecter) ListAll(ctx interface{}, limit interface{}, offset interface{}) *AutoBuyRuleRepository_ListAll_Call {
	return &AutoBuyRuleRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx, limit, offset)}
}

func (_c *AutoBuyRuleRepository_ListAll_Call) Run(run func(ctx context.Context, limit int, offset int)) *AutoBuyRuleRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *AutoBuyRuleRepository_ListAll_Call) Return(_a0 []*model.AutoBuyRule, _a1 error) *AutoBuyRuleRepository_ListAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AutoBuyRuleRepository_ListAll_Call) RunAndReturn(run func(context.Context, int, int) ([]*model.AutoBuyRule, error)) *AutoBuyRuleRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, rule
func (_m *AutoBuyRuleRepository) Update(ctx context.Context, rule *model.AutoBuyRule) error {
	ret := _m.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AutoBuyRule) error); ok {
		r0 = rf(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AutoBuyRuleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type AutoBuyRuleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - rule *model.AutoBuyRule
func (_e *AutoBuyRuleRepository_Expecter) Update(ctx interface{}, rule interface{}) *AutoBuyRuleRepository_Update_Call {
	return &AutoBuyRuleRepository_Update_Call{Call: _e.mock.On("Update", ctx, rule)}
}

func (_c *AutoBuyRuleRepository_Update_Call) Run(run func(ctx context.Context, rule *model.AutoBuyRule)) *AutoBuyRuleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.AutoBuyRule))
	})
	return _c
}

func (_c *AutoBuyRuleRepository_Update_Call) Return(_a0 error) *AutoBuyRuleRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AutoBuyRuleRepository_Update_Call) RunAndReturn(run func(context.Context, *model.AutoBuyRule) error) *AutoBuyRuleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewAutoBuyRuleRepository creates a new instance of AutoBuyRuleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAutoBuyRuleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AutoBuyRuleRepository {
	mock := &AutoBuyRuleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
