// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	model "github.com/RyanLisse/go-crypto-bot-clean/clean_backend/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// AutoBuyExecutionRepository is an autogenerated mock type for the AutoBuyExecutionRepository type
type AutoBuyExecutionRepository struct {
	mock.Mock
}

type AutoBuyExecutionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AutoBuyExecutionRepository) EXPECT() *AutoBuyExecutionRepository_Expecter {
	return &AutoBuyExecutionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, execution
func (_m *AutoBuyExecutionRepository) Create(ctx context.Context, execution *model.AutoBuyExecution) error {
	ret := _m.Called(ctx, execution)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AutoBuyExecution) error); ok {
		r0 = rf(ctx, execution)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AutoBuyExecutionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AutoBuyExecutionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - execution *model.AutoBuyExecution
func (_e *AutoBuyExecutionRepository_Expecter) Create(ctx interface{}, execution interface{}) *AutoBuyExecutionRepository_Create_Call {
	return &AutoBuyExecutionRepository_Create_Call{Call: _e.mock.On("Create", ctx, execution)}
}

func (_c *AutoBuyExecutionRepository_Create_Call) Run(run func(ctx context.Context, execution *model.AutoBuyExecution)) *AutoBuyExecutionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.AutoBuyExecution))
	})
	return _c
}

func (_c *AutoBuyExecutionRepository_Create_Call) Return(_a0 error) *AutoBuyExecutionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AutoBuyExecutionRepository_Create_Call) RunAndReturn(run func(context.Context, *model.AutoBuyExecution) error) *AutoBuyExecutionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *AutoBuyExecutionRepository) GetByID(ctx context.Context, id string) (*model.AutoBuyExecution, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.AutoBuyExecution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.AutoBuyExecution, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.AutoBuyExecution); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AutoBuyExecution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AutoBuyExecutionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type AutoBuyExecutionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *AutoBuyExecutionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *AutoBuyExecutionRepository_GetByID_Call {
	return &AutoBuyExecutionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *AutoBuyExecutionRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *AutoBuyExecutionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AutoBuyExecutionRepository_GetByID_Call) Return(_a0 *model.AutoBuyExecution, _a1 error) *AutoBuyExecutionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AutoBuyExecutionRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*model.AutoBuyExecution, error)) *AutoBuyExecutionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByRuleID provides a mock function with given fields: ctx, ruleID, limit, offset
func (_m *AutoBuyExecutionRepository) GetByRuleID(ctx context.Context, ruleID string, limit int, offset int) ([]*model.AutoBuyExecution, error) {
	ret := _m.Called(ctx, ruleID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByRuleID")
	}

	var r0 []*model.AutoBuyExecution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*model.AutoBuyExecution, error)); ok {
		return rf(ctx, ruleID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*model.AutoBuyExecution); ok {
		r0 = rf(ctx, ruleID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AutoBuyExecution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, ruleID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AutoBuyExecutionRepository_GetByRuleID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByRuleID'
type AutoBuyExecutionRepository_GetByRuleID_Call struct {
	*mock.Call
}

// GetByRuleID is a helper method to define mock.On call
//   - ctx context.Context
//   - ruleID string
//   - limit int
//   - offset int
func (_e *AutoBuyExecutionRepository_Expecter) GetByRuleID(ctx interface{}, ruleID interface{}, limit interface{}, offset interface{}) *AutoBuyExecutionRepository_GetByRuleID_Call {
	return &AutoBuyExecutionRepository_GetByRuleID_Call{Call: _e.mock.On("GetByRuleID", ctx, ruleID, limit, offset)}
}

func (_c *AutoBuyExecutionRepository_GetByRuleID_Call) Run(run func(ctx context.Context, ruleID string, limit int, offset int)) *AutoBuyExecutionRepository_GetByRuleID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *AutoBuyExecutionRepository_GetByRuleID_Call) Return(_a0 []*model.AutoBuyExecution, _a1 error) *AutoBuyExecutionRepository_GetByRuleID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AutoBuyExecutionRepository_GetByRuleID_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*model.AutoBuyExecution, error)) *AutoBuyExecutionRepository_GetByRuleID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySymbol provides a mock function with given fields: ctx, symbol, limit, offset
func (_m *AutoBuyExecutionRepository) GetBySymbol(ctx context.Context, symbol string, limit int, offset int) ([]*model.AutoBuyExecution, error) {
	ret := _m.Called(ctx, symbol, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetBySymbol")
	}

	var r0 []*model.AutoBuyExecution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*model.AutoBuyExecution, error)); ok {
		return rf(ctx, symbol, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*model.AutoBuyExecution); ok {
		r0 = rf(ctx, symbol, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AutoBuyExecution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, symbol, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AutoBuyExecutionRepository_GetBySymbol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySymbol'
type AutoBuyExecutionRepository_GetBySymbol_Call struct {
	*mock.Call
}

// GetBySymbol is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - limit int
//   - offset int
func (_e *AutoBuyExecutionRepository_Expecter) GetBySymbol(ctx interface{}, symbol interface{}, limit interface{}, offset interface{}) *AutoBuyExecutionRepository_GetBySymbol_Call {
	return &AutoBuyExecutionRepository_GetBySymbol_Call{Call: _e.mock.On("GetBySymbol", ctx, symbol, limit, offset)}
}

func (_c *AutoBuyExecutionRepository_GetBySymbol_Call) Run(run func(ctx context.Context, symbol string, limit int, offset int)) *AutoBuyExecutionRepository_GetBySymbol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *AutoBuyExecutionRepository_GetBySymbol_Call) Return(_a0 []*model.AutoBuyExecution, _a1 error) *AutoBuyExecutionRepository_GetBySymbol_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AutoBuyExecutionRepository_GetBySymbol_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*model.AutoBuyExecution, error)) *AutoBuyExecutionRepository_GetBySymbol_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTimeRange provides a mock function with given fields: ctx, from, to, limit, offset
func (_m *AutoBuyExecutionRepository) GetByTimeRange(ctx context.Context, from time.Time, to time.Time, limit int, offset int) ([]*model.AutoBuyExecution, error) {
	ret := _m.Called(ctx, from, to, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByTimeRange")
	}

	var r0 []*model.AutoBuyExecution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) ([]*model.AutoBuyExecution, error)); ok {
		return rf(ctx, from, to, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) []*model.AutoBuyExecution); ok {
		r0 = rf(ctx, from, to, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AutoBuyExecution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, int, int) error); ok {
		r1 = rf(ctx, from, to, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AutoBuyExecutionRepository_GetByTimeRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTimeRange'
type AutoBuyExecutionRepository_GetByTimeRange_Call struct {
	*mock.Call
}

// GetByTimeRange is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
//   - limit int
//   - offset int
func (_e *AutoBuyExecutionRepository_Expecter) GetByTimeRange(ctx interface{}, from interface{}, to interface{}, limit interface{}, offset interface{}) *AutoBuyExecutionRepository_GetByTimeRange_Call {
	return &AutoBuyExecutionRepository_GetByTimeRange_Call{Call: _e.mock.On("GetByTimeRange", ctx, from, to, limit, offset)}
}

func (_c *AutoBuyExecutionRepository_GetByTimeRange_Call) Run(run func(ctx context.Context, from time.Time, to time.Time, limit int, offset int)) *AutoBuyExecutionRepository_GetByTimeRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *AutoBuyExecutionRepository_GetByTimeRange_Call) Return(_a0 []*model.AutoBuyExecution, _a1 error) *AutoBuyExecutionRepository_GetByTimeRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AutoBuyExecutionRepository_GetByTimeRange_Call) RunAndReturn(run func(context.Context, time.Time, time.Time, int, int) ([]*model.AutoBuyExecution, error)) *AutoBuyExecutionRepository_GetByTimeRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID, limit, offset
func (_m *AutoBuyExecutionRepository) GetByUserID(ctx context.Context, userID string, limit int, offset int) ([]*model.AutoBuyExecution, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*model.AutoBuyExecution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*model.AutoBuyExecution, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*model.AutoBuyExecution); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AutoBuyExecution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AutoBuyExecutionRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type AutoBuyExecutionRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
func (_e *AutoBuyExecutionRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *AutoBuyExecutionRepository_GetByUserID_Call {
	return &AutoBuyExecutionRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID, limit, offset)}
}

func (_c *AutoBuyExecutionRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID string, limit int, offset int)) *AutoBuyExecutionRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *AutoBuyExecutionRepository_GetByUserID_Call) Return(_a0 []*model.AutoBuyExecution, _a1 error) *AutoBuyExecutionRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AutoBuyExecutionRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*model.AutoBuyExecution, error)) *AutoBuyExecutionRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewAutoBuyExecutionRepository creates a new instance of AutoBuyExecutionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAutoBuyExecutionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AutoBuyExecutionRepository {
	mock := &AutoBuyExecutionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
