// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/RyanLisse/go-crypto-bot-clean/clean_backend/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// NewCoinRepository is an autogenerated mock type for the NewCoinRepository type
type NewCoinRepository struct {
	mock.Mock
}

type NewCoinRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *NewCoinRepository) EXPECT() *NewCoinRepository_Expecter {
	return &NewCoinRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: coin
func (_m *NewCoinRepository) Create(coin *model.NewCoin) error {
	ret := _m.Called(coin)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.NewCoin) error); ok {
		r0 = rf(coin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCoinRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type NewCoinRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - coin *model.NewCoin
func (_e *NewCoinRepository_Expecter) Create(coin interface{}) *NewCoinRepository_Create_Call {
	return &NewCoinRepository_Create_Call{Call: _e.mock.On("Create", coin)}
}

func (_c *NewCoinRepository_Create_Call) Run(run func(coin *model.NewCoin)) *NewCoinRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.NewCoin))
	})
	return _c
}

func (_c *NewCoinRepository_Create_Call) Return(_a0 error) *NewCoinRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NewCoinRepository_Create_Call) RunAndReturn(run func(*model.NewCoin) error) *NewCoinRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEvent provides a mock function with given fields: event
func (_m *NewCoinRepository) CreateEvent(event *model.NewCoinEvent) error {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.NewCoinEvent) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCoinRepository_CreateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvent'
type NewCoinRepository_CreateEvent_Call struct {
	*mock.Call
}

// CreateEvent is a helper method to define mock.On call
//   - event *model.NewCoinEvent
func (_e *NewCoinRepository_Expecter) CreateEvent(event interface{}) *NewCoinRepository_CreateEvent_Call {
	return &NewCoinRepository_CreateEvent_Call{Call: _e.mock.On("CreateEvent", event)}
}

func (_c *NewCoinRepository_CreateEvent_Call) Run(run func(event *model.NewCoinEvent)) *NewCoinRepository_CreateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.NewCoinEvent))
	})
	return _c
}

func (_c *NewCoinRepository_CreateEvent_Call) Return(_a0 error) *NewCoinRepository_CreateEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NewCoinRepository_CreateEvent_Call) RunAndReturn(run func(*model.NewCoinEvent) error) *NewCoinRepository_CreateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *NewCoinRepository) GetByID(ctx context.Context, id string) (*model.NewCoin, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.NewCoin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.NewCoin, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.NewCoin); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.NewCoin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCoinRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type NewCoinRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *NewCoinRepository_Expecter) GetByID(ctx interface{}, id interface{}) *NewCoinRepository_GetByID_Call {
	return &NewCoinRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *NewCoinRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *NewCoinRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *NewCoinRepository_GetByID_Call) Return(_a0 *model.NewCoin, _a1 error) *NewCoinRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NewCoinRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*model.NewCoin, error)) *NewCoinRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySymbol provides a mock function with given fields: symbol
func (_m *NewCoinRepository) GetBySymbol(symbol string) (*model.NewCoin, error) {
	ret := _m.Called(symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetBySymbol")
	}

	var r0 *model.NewCoin
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.NewCoin, error)); ok {
		return rf(symbol)
	}
	if rf, ok := ret.Get(0).(func(string) *model.NewCoin); ok {
		r0 = rf(symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.NewCoin)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCoinRepository_GetBySymbol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySymbol'
type NewCoinRepository_GetBySymbol_Call struct {
	*mock.Call
}

// GetBySymbol is a helper method to define mock.On call
//   - symbol string
func (_e *NewCoinRepository_Expecter) GetBySymbol(symbol interface{}) *NewCoinRepository_GetBySymbol_Call {
	return &NewCoinRepository_GetBySymbol_Call{Call: _e.mock.On("GetBySymbol", symbol)}
}

func (_c *NewCoinRepository_GetBySymbol_Call) Run(run func(symbol string)) *NewCoinRepository_GetBySymbol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *NewCoinRepository_GetBySymbol_Call) Return(_a0 *model.NewCoin, _a1 error) *NewCoinRepository_GetBySymbol_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NewCoinRepository_GetBySymbol_Call) RunAndReturn(run func(string) (*model.NewCoin, error)) *NewCoinRepository_GetBySymbol_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvents provides a mock function with given fields: coinID, limit, offset
func (_m *NewCoinRepository) GetEvents(coinID string, limit int, offset int) ([]*model.NewCoinEvent, error) {
	ret := _m.Called(coinID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetEvents")
	}

	var r0 []*model.NewCoinEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) ([]*model.NewCoinEvent, error)); ok {
		return rf(coinID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) []*model.NewCoinEvent); ok {
		r0 = rf(coinID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.NewCoinEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(coinID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCoinRepository_GetEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvents'
type NewCoinRepository_GetEvents_Call struct {
	*mock.Call
}

// GetEvents is a helper method to define mock.On call
//   - coinID string
//   - limit int
//   - offset int
func (_e *NewCoinRepository_Expecter) GetEvents(coinID interface{}, limit interface{}, offset interface{}) *NewCoinRepository_GetEvents_Call {
	return &NewCoinRepository_GetEvents_Call{Call: _e.mock.On("GetEvents", coinID, limit, offset)}
}

func (_c *NewCoinRepository_GetEvents_Call) Run(run func(coinID string, limit int, offset int)) *NewCoinRepository_GetEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *NewCoinRepository_GetEvents_Call) Return(_a0 []*model.NewCoinEvent, _a1 error) *NewCoinRepository_GetEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NewCoinRepository_GetEvents_Call) RunAndReturn(run func(string, int, int) ([]*model.NewCoinEvent, error)) *NewCoinRepository_GetEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecent provides a mock function with given fields: limit
func (_m *NewCoinRepository) GetRecent(limit int) ([]*model.NewCoin, error) {
	ret := _m.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecent")
	}

	var r0 []*model.NewCoin
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*model.NewCoin, error)); ok {
		return rf(limit)
	}
	if rf, ok := ret.Get(0).(func(int) []*model.NewCoin); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.NewCoin)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCoinRepository_GetRecent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecent'
type NewCoinRepository_GetRecent_Call struct {
	*mock.Call
}

// GetRecent is a helper method to define mock.On call
//   - limit int
func (_e *NewCoinRepository_Expecter) GetRecent(limit interface{}) *NewCoinRepository_GetRecent_Call {
	return &NewCoinRepository_GetRecent_Call{Call: _e.mock.On("GetRecent", limit)}
}

func (_c *NewCoinRepository_GetRecent_Call) Run(run func(limit int)) *NewCoinRepository_GetRecent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *NewCoinRepository_GetRecent_Call) Return(_a0 []*model.NewCoin, _a1 error) *NewCoinRepository_GetRecent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NewCoinRepository_GetRecent_Call) RunAndReturn(run func(int) ([]*model.NewCoin, error)) *NewCoinRepository_GetRecent_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: status, limit, offset
func (_m *NewCoinRepository) List(status model.CoinStatus, limit int, offset int) ([]*model.NewCoin, error) {
	ret := _m.Called(status, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.NewCoin
	var r1 error
	if rf, ok := ret.Get(0).(func(model.CoinStatus, int, int) ([]*model.NewCoin, error)); ok {
		return rf(status, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(model.CoinStatus, int, int) []*model.NewCoin); ok {
		r0 = rf(status, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.NewCoin)
		}
	}

	if rf, ok := ret.Get(1).(func(model.CoinStatus, int, int) error); ok {
		r1 = rf(status, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCoinRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type NewCoinRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - status model.CoinStatus
//   - limit int
//   - offset int
func (_e *NewCoinRepository_Expecter) List(status interface{}, limit interface{}, offset interface{}) *NewCoinRepository_List_Call {
	return &NewCoinRepository_List_Call{Call: _e.mock.On("List", status, limit, offset)}
}

func (_c *NewCoinRepository_List_Call) Run(run func(status model.CoinStatus, limit int, offset int)) *NewCoinRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.CoinStatus), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *NewCoinRepository_List_Call) Return(_a0 []*model.NewCoin, _a1 error) *NewCoinRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NewCoinRepository_List_Call) RunAndReturn(run func(model.CoinStatus, int, int) ([]*model.NewCoin, error)) *NewCoinRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: coin
func (_m *NewCoinRepository) Update(coin *model.NewCoin) error {
	ret := _m.Called(coin)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.NewCoin) error); ok {
		r0 = rf(coin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCoinRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type NewCoinRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - coin *model.NewCoin
func (_e *NewCoinRepository_Expecter) Update(coin interface{}) *NewCoinRepository_Update_Call {
	return &NewCoinRepository_Update_Call{Call: _e.mock.On("Update", coin)}
}

func (_c *NewCoinRepository_Update_Call) Run(run func(coin *model.NewCoin)) *NewCoinRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.NewCoin))
	})
	return _c
}

func (_c *NewCoinRepository_Update_Call) Return(_a0 error) *NewCoinRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NewCoinRepository_Update_Call) RunAndReturn(run func(*model.NewCoin) error) *NewCoinRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewNewCoinRepository creates a new instance of NewCoinRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNewCoinRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NewCoinRepository {
	mock := &NewCoinRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
