server:
  port: 8080
  host: "0.0.0.0"
  timeout: 30s
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 60s
  max_header_bytes: 1048576 # 1MB
  shutdown_timeout: 30s

auth:
  jwt_secret: "${JWT_SECRET}"
  jwt_expiry: "${JWT_EXPIRY}"
  cookie_name: "crypto_bot_auth"
  cookie_secure: true
  cookie_http_only: true
  api_keys: []  # API keys should be loaded from environment variables

cors:
  enabled: true
  allowed_origins: "${ALLOWED_ORIGINS}"
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["Authorization", "Content-Type", "X-API-Key"]
  exposed_headers: []
  allow_credentials: true
  max_age: 300

rate_limit:
  enabled: true
  requests: "${RATE_LIMIT_REQUESTS}"
  window: "${RATE_LIMIT_WINDOW}"
  strategy: "ip"

logging:
  level: "${LOG_LEVEL}"
  format: "json"
  output: "stdout"
  enable_stacktrace: false

mexc:
  api_key: "${MEXC_API_KEY}"
  secret_key: "${MEXC_SECRET_KEY}"
  base_url: "${MEXC_BASE_URL}"
  websocket_url: "${MEXC_WEBSOCKET_URL}"
  timeout: 10s
  retry_attempts: 3
  retry_delay: 500ms

database:
  turso:
    enabled: "${TURSO_ENABLED}"
    url: "${TURSO_URL}"
    auth_token: "${TURSO_AUTH_TOKEN}"
    sync_enabled: "${TURSO_SYNC_ENABLED}"
    sync_interval: "${TURSO_SYNC_INTERVAL_SECONDS}s"

ai:
  openai:
    api_key: "${OPENAI_API_KEY}"
    model: "gpt-4"
    temperature: 0.7
    max_tokens: 2048
  anthropic:
    api_key: "${ANTHROPIC_API_KEY}"
    model: "claude-2"
  nomic:
    api_key: "${NOMIC_API_KEY}"

security:
  ssl:
    enabled: true
    cert_file: "/etc/ssl/certs/app.crt"
    key_file: "/etc/ssl/private/app.key"
  headers:
    content_security_policy: "default-src 'self'; script-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self'"
    x_content_type_options: "nosniff"
    x_frame_options: "DENY"
    x_xss_protection: "1; mode=block"
    referrer_policy: "strict-origin-when-cross-origin"
    strict_transport_security: "max-age=31536000; includeSubDomains"
