name: Go CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: go mod download
      - name: Lint
        run: go vet ./...
      - name: Test
        run: go test -v -coverprofile=coverage.out ./...
      - name: Check test coverage
        run: |
          go tool cover -func=coverage.out | grep total | awk '{print $3}'
      - name: Pre-commit checks
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: run --all-files
