// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SimplePriceChecker is an autogenerated mock type for the SimplePriceChecker type
type SimplePriceChecker struct {
	mock.Mock
}

type SimplePriceChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *SimplePriceChecker) EXPECT() *SimplePriceChecker_Expecter {
	return &SimplePriceChecker_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, symbol
func (_m *SimplePriceChecker) Execute(ctx context.Context, symbol string) (float64, error) {
	ret := _m.Called(ctx, symbol)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return rf(ctx, symbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, symbol)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SimplePriceChecker_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type SimplePriceChecker_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
func (_e *SimplePriceChecker_Expecter) Execute(ctx interface{}, symbol interface{}) *SimplePriceChecker_Execute_Call {
	return &SimplePriceChecker_Execute_Call{Call: _e.mock.On("Execute", ctx, symbol)}
}

func (_c *SimplePriceChecker_Execute_Call) Run(run func(ctx context.Context, symbol string)) *SimplePriceChecker_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SimplePriceChecker_Execute_Call) Return(_a0 float64, _a1 error) *SimplePriceChecker_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SimplePriceChecker_Execute_Call) RunAndReturn(run func(context.Context, string) (float64, error)) *SimplePriceChecker_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewSimplePriceChecker creates a new instance of SimplePriceChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSimplePriceChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *SimplePriceChecker {
	mock := &SimplePriceChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
