#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get the list of staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|jsx|ts|tsx)$')

# If there are no staged files, exit
if [ -z "$STAGED_FILES" ]; then
  echo "No frontend files to lint or test."
else
  echo "Running frontend linting and tests..."
  cd frontend && bun run lint && bun run test
fi

# Check if there are any Go files staged
GO_STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.go$')

# If there are Go files staged, run Go tests
if [ -z "$GO_STAGED_FILES" ]; then
  echo "No Go files to test."
else
  echo "Running Go tests..."
  cd backend && go test ./...
fi
