app:
  name: "Go Crypto Bot"
  environment: "production"
  log_level: "info"
  debug: false
  port: "8081"

logging:
  file_path: "/app/data/logs"
  max_size: 10
  max_backups: 3
  max_age: 30

database:
  enabled: true
  path: "./data/minimal.db"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime_seconds: 300
  turso:
    enabled: false
    url: ""
    auth_token: ""
    sync_enabled: false
    sync_interval_seconds: 60
    batch_size: 100
    max_retries: 3
    retry_delay_seconds: 5

auth:
  enabled: false
  jwt_secret: ""
  jwt_expiry: 24
  cookie_name: "auth_token"
  clerk_secret_key: ""
  clerk_domain: ""
