app:
  name: go-crypto-bot
  environment: development
  log_level: info

auth:
  enabled: false
  jwt_secret: "your-secret-key-change-this-in-production"
  jwt_expiry: 24  # in hours
  cookie_name: "crypto_bot_auth"
  api_keys:
    - "test-api-key-1"
    - "test-api-key-2"

ai_providers:
  openai:
    api_key: "" # Set via environment variable OPENAI_API_KEY
  google:
    api_key: "" # Set via environment variable GOOGLE_API_KEY

mexc:
  api_key: "" # Set via environment variable MEXC_API_KEY
  secret_key: "" # Set via environment variable MEXC_SECRET_KEY
  base_url: "https://api.mexc.com/api/v3" # Can be overridden with MEXC_BASE_URL
  websocket_url: "wss://wbs.mexc.com/ws" # Can be overridden with MEXC_WEBSOCKET_URL

websocket:
  reconnect_delay: 5s
  max_reconnect_attempts: 10
  ping_interval: 30s

connection_rate_limiter:
  requests_per_second: 10
  burst_capacity: 20

subscription_rate_limiter:
  requests_per_second: 10
  burst_capacity: 20

trading:
  default_symbol: "BTCUSDT"
  default_order_type: "MARKET"
  default_quantity: 0.001

logging:
  file_path: "./logs/app.log"
  max_size: 100  # MB
  max_backups: 3
  max_age: 28   # days

database:
  type: sqlite
  path: "./data/trading.db"
  maxOpenConns: 10
  maxIdleConns: 5
  connMaxLifetimeSeconds: 300

  # TursoDB configuration
  turso:
    enabled: true
    url: "" # Set via environment variable TURSO_URL
    authToken: "" # Set via environment variable TURSO_AUTH_TOKEN
    syncEnabled: true
    syncIntervalSeconds: 300

  # Shadow mode configuration
  # When enabled, writes to both SQLite and TursoDB, but reads from SQLite
  # This allows for a gradual migration to TursoDB while ensuring data consistency
  shadowMode: true
