# Server configuration
server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

# Environment
env: "development"
log_level: "info"

# Database configuration
database:
  driver: "sqlite"
  path: "./data/crypto_bot.db"
  turso:
    enabled: true
    url: "${TURSO_URL}"
    auth_token: "${TURSO_AUTH_TOKEN}"

# MEXC API configuration
mexc:
  api_key: "${MEXC_API_KEY}"
  api_secret: "${MEXC_SECRET_KEY}"
  base_url: "${MEXC_BASE_URL}"
  ws_base_url: "${MEXC_WEBSOCKET_URL}"
  use_testnet: false
  rate_limit:
    requests_per_minute: 1200
    burst_size: 10

# AI configuration
ai:
  provider: "gemini"
  api_key: "${OPENAI_API_KEY}"
  model: "gpt-4"
  gemini_api_key: "${GOOGLE_API_KEY}"
  gemini_model: "gemini-1.5-flash"
  system_prompt: "You are a crypto trading assistant. You help users understand their portfolio, market trends, and provide trading advice. Keep responses concise and focused on crypto trading."
  temperature: 0.7
  top_p: 0.95
  top_k: 40
  max_tokens: 1024
